/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "wendy_conf.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(WendyConfWifiNetwork, WendyConfWifiNetwork, AUTO)


PB_BIND(WendyConfWifi, WendyConfWifi, AUTO)


PB_BIND(WendyConfCloudProvisioning, WendyConfCloudProvisioning, AUTO)


PB_BIND(WendyConf, WendyConf, AUTO)





