// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.0
// source: wendy_com_relay_service.proto

package wcomrelaypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_wendy_com_relay_service_proto protoreflect.FileDescriptor

const file_wendy_com_relay_service_proto_rawDesc = "" +
	"\n" +
	"\x1dwendy_com_relay_service.proto\x1a\x19wendy_com_relay_msg.proto2Y\n" +
	"\x14WendyComRelayService\x12A\n" +
	"\rWendyComRelay\x12\x15.WendyComRelayMessage\x1a\x15.WendyComRelayMessage(\x010\x01b\x06proto3"

var file_wendy_com_relay_service_proto_goTypes = []any{
	(*WendyComRelayMessage)(nil), // 0: WendyComRelayMessage
}
var file_wendy_com_relay_service_proto_depIdxs = []int32{
	0, // 0: WendyComRelayService.WendyComRelay:input_type -> WendyComRelayMessage
	0, // 1: WendyComRelayService.WendyComRelay:output_type -> WendyComRelayMessage
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wendy_com_relay_service_proto_init() }
func file_wendy_com_relay_service_proto_init() {
	if File_wendy_com_relay_service_proto != nil {
		return
	}
	file_wendy_com_relay_msg_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wendy_com_relay_service_proto_rawDesc), len(file_wendy_com_relay_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wendy_com_relay_service_proto_goTypes,
		DependencyIndexes: file_wendy_com_relay_service_proto_depIdxs,
	}.Build()
	File_wendy_com_relay_service_proto = out.File
	file_wendy_com_relay_service_proto_goTypes = nil
	file_wendy_com_relay_service_proto_depIdxs = nil
}
