// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.0
// source: wendy_com_relay_service.proto

package wcomrelaypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WendyComRelayService_WendyComRelay_FullMethodName = "/WendyComRelayService/WendyComRelay"
)

// WendyComRelayServiceClient is the client API for WendyComRelayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WendyComRelayServiceClient interface {
	// The client's first message must be open; everything after, in both
	// directions, is payload. Stream lifetime == channel lifetime.
	WendyComRelay(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WendyComRelayMessage, WendyComRelayMessage], error)
}

type wendyComRelayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWendyComRelayServiceClient(cc grpc.ClientConnInterface) WendyComRelayServiceClient {
	return &wendyComRelayServiceClient{cc}
}

func (c *wendyComRelayServiceClient) WendyComRelay(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WendyComRelayMessage, WendyComRelayMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WendyComRelayService_ServiceDesc.Streams[0], WendyComRelayService_WendyComRelay_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WendyComRelayMessage, WendyComRelayMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WendyComRelayService_WendyComRelayClient = grpc.BidiStreamingClient[WendyComRelayMessage, WendyComRelayMessage]

// WendyComRelayServiceServer is the server API for WendyComRelayService service.
// All implementations must embed UnimplementedWendyComRelayServiceServer
// for forward compatibility.
type WendyComRelayServiceServer interface {
	// The client's first message must be open; everything after, in both
	// directions, is payload. Stream lifetime == channel lifetime.
	WendyComRelay(grpc.BidiStreamingServer[WendyComRelayMessage, WendyComRelayMessage]) error
	mustEmbedUnimplementedWendyComRelayServiceServer()
}

// UnimplementedWendyComRelayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWendyComRelayServiceServer struct{}

func (UnimplementedWendyComRelayServiceServer) WendyComRelay(grpc.BidiStreamingServer[WendyComRelayMessage, WendyComRelayMessage]) error {
	return status.Error(codes.Unimplemented, "method WendyComRelay not implemented")
}
func (UnimplementedWendyComRelayServiceServer) mustEmbedUnimplementedWendyComRelayServiceServer() {}
func (UnimplementedWendyComRelayServiceServer) testEmbeddedByValue()                              {}

// UnsafeWendyComRelayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WendyComRelayServiceServer will
// result in compilation errors.
type UnsafeWendyComRelayServiceServer interface {
	mustEmbedUnimplementedWendyComRelayServiceServer()
}

func RegisterWendyComRelayServiceServer(s grpc.ServiceRegistrar, srv WendyComRelayServiceServer) {
	// If the following call panics, it indicates UnimplementedWendyComRelayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WendyComRelayService_ServiceDesc, srv)
}

func _WendyComRelayService_WendyComRelay_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WendyComRelayServiceServer).WendyComRelay(&grpc.GenericServerStream[WendyComRelayMessage, WendyComRelayMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WendyComRelayService_WendyComRelayServer = grpc.BidiStreamingServer[WendyComRelayMessage, WendyComRelayMessage]

// WendyComRelayService_ServiceDesc is the grpc.ServiceDesc for WendyComRelayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WendyComRelayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "WendyComRelayService",
	HandlerType: (*WendyComRelayServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WendyComRelay",
			Handler:       _WendyComRelayService_WendyComRelay_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "wendy_com_relay_service.proto",
}
