// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.0
// source: wendy_com_relay_msg.proto

package wcomrelaypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// First and only non-payload client message on a relay stream. Identifies
// the target device by its asset UUID. The development relay trusts this
// value; a deployed broker must authorize the caller for that asset first.
type WendyComRelayOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComRelayOpen) Reset() {
	*x = WendyComRelayOpen{}
	mi := &file_wendy_com_relay_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComRelayOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComRelayOpen) ProtoMessage() {}

func (x *WendyComRelayOpen) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_relay_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComRelayOpen.ProtoReflect.Descriptor instead.
func (*WendyComRelayOpen) Descriptor() ([]byte, []int) {
	return file_wendy_com_relay_msg_proto_rawDescGZIP(), []int{0}
}

func (x *WendyComRelayOpen) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

// One bare protobuf-encoded WendyComMessage body — no 8-byte link header.
// The broker adds/strips the header and owns the channel byte.
type WendyComRelayPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bytes         []byte                 `protobuf:"bytes,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComRelayPayload) Reset() {
	*x = WendyComRelayPayload{}
	mi := &file_wendy_com_relay_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComRelayPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComRelayPayload) ProtoMessage() {}

func (x *WendyComRelayPayload) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_relay_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComRelayPayload.ProtoReflect.Descriptor instead.
func (*WendyComRelayPayload) Descriptor() ([]byte, []int) {
	return file_wendy_com_relay_msg_proto_rawDescGZIP(), []int{1}
}

func (x *WendyComRelayPayload) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

type WendyComRelayMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*WendyComRelayMessage_Open
	//	*WendyComRelayMessage_Payload
	Msg           isWendyComRelayMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComRelayMessage) Reset() {
	*x = WendyComRelayMessage{}
	mi := &file_wendy_com_relay_msg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComRelayMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComRelayMessage) ProtoMessage() {}

func (x *WendyComRelayMessage) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_relay_msg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComRelayMessage.ProtoReflect.Descriptor instead.
func (*WendyComRelayMessage) Descriptor() ([]byte, []int) {
	return file_wendy_com_relay_msg_proto_rawDescGZIP(), []int{2}
}

func (x *WendyComRelayMessage) GetMsg() isWendyComRelayMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *WendyComRelayMessage) GetOpen() *WendyComRelayOpen {
	if x != nil {
		if x, ok := x.Msg.(*WendyComRelayMessage_Open); ok {
			return x.Open
		}
	}
	return nil
}

func (x *WendyComRelayMessage) GetPayload() *WendyComRelayPayload {
	if x != nil {
		if x, ok := x.Msg.(*WendyComRelayMessage_Payload); ok {
			return x.Payload
		}
	}
	return nil
}

type isWendyComRelayMessage_Msg interface {
	isWendyComRelayMessage_Msg()
}

type WendyComRelayMessage_Open struct {
	Open *WendyComRelayOpen `protobuf:"bytes,1,opt,name=open,proto3,oneof"`
}

type WendyComRelayMessage_Payload struct {
	Payload *WendyComRelayPayload `protobuf:"bytes,2,opt,name=payload,proto3,oneof"`
}

func (*WendyComRelayMessage_Open) isWendyComRelayMessage_Msg() {}

func (*WendyComRelayMessage_Payload) isWendyComRelayMessage_Msg() {}

var File_wendy_com_relay_msg_proto protoreflect.FileDescriptor

const file_wendy_com_relay_msg_proto_rawDesc = "" +
	"\n" +
	"\x19wendy_com_relay_msg.proto\".\n" +
	"\x11WendyComRelayOpen\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\",\n" +
	"\x14WendyComRelayPayload\x12\x14\n" +
	"\x05bytes\x18\x01 \x01(\fR\x05bytes\"z\n" +
	"\x14WendyComRelayMessage\x12(\n" +
	"\x04open\x18\x01 \x01(\v2\x12.WendyComRelayOpenH\x00R\x04open\x121\n" +
	"\apayload\x18\x02 \x01(\v2\x15.WendyComRelayPayloadH\x00R\apayloadB\x05\n" +
	"\x03msgb\x06proto3"

var (
	file_wendy_com_relay_msg_proto_rawDescOnce sync.Once
	file_wendy_com_relay_msg_proto_rawDescData []byte
)

func file_wendy_com_relay_msg_proto_rawDescGZIP() []byte {
	file_wendy_com_relay_msg_proto_rawDescOnce.Do(func() {
		file_wendy_com_relay_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wendy_com_relay_msg_proto_rawDesc), len(file_wendy_com_relay_msg_proto_rawDesc)))
	})
	return file_wendy_com_relay_msg_proto_rawDescData
}

var file_wendy_com_relay_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_wendy_com_relay_msg_proto_goTypes = []any{
	(*WendyComRelayOpen)(nil),    // 0: WendyComRelayOpen
	(*WendyComRelayPayload)(nil), // 1: WendyComRelayPayload
	(*WendyComRelayMessage)(nil), // 2: WendyComRelayMessage
}
var file_wendy_com_relay_msg_proto_depIdxs = []int32{
	0, // 0: WendyComRelayMessage.open:type_name -> WendyComRelayOpen
	1, // 1: WendyComRelayMessage.payload:type_name -> WendyComRelayPayload
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_wendy_com_relay_msg_proto_init() }
func file_wendy_com_relay_msg_proto_init() {
	if File_wendy_com_relay_msg_proto != nil {
		return
	}
	file_wendy_com_relay_msg_proto_msgTypes[2].OneofWrappers = []any{
		(*WendyComRelayMessage_Open)(nil),
		(*WendyComRelayMessage_Payload)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wendy_com_relay_msg_proto_rawDesc), len(file_wendy_com_relay_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wendy_com_relay_msg_proto_goTypes,
		DependencyIndexes: file_wendy_com_relay_msg_proto_depIdxs,
		MessageInfos:      file_wendy_com_relay_msg_proto_msgTypes,
	}.Build()
	File_wendy_com_relay_msg_proto = out.File
	file_wendy_com_relay_msg_proto_goTypes = nil
	file_wendy_com_relay_msg_proto_depIdxs = nil
}
