/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_WENDY_LITE_SENSORLINK_SENSORLINK_PB_H_INCLUDED
#define PB_WENDY_LITE_SENSORLINK_SENSORLINK_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _wendy_lite_sensorlink_VideoFormat_Codec {
    wendy_lite_sensorlink_VideoFormat_Codec_CODEC_UNSPECIFIED = 0,
    wendy_lite_sensorlink_VideoFormat_Codec_MJPEG = 1,
    wendy_lite_sensorlink_VideoFormat_Codec_H264 = 2
} wendy_lite_sensorlink_VideoFormat_Codec;

typedef enum _wendy_lite_sensorlink_AudioFormat_Codec {
    wendy_lite_sensorlink_AudioFormat_Codec_CODEC_UNSPECIFIED = 0,
    wendy_lite_sensorlink_AudioFormat_Codec_PCM_S16LE = 1,
    wendy_lite_sensorlink_AudioFormat_Codec_OPUS = 2
} wendy_lite_sensorlink_AudioFormat_Codec;

typedef enum _wendy_lite_sensorlink_SensorDescriptor_Kind {
    wendy_lite_sensorlink_SensorDescriptor_Kind_KIND_UNSPECIFIED = 0,
    wendy_lite_sensorlink_SensorDescriptor_Kind_CAMERA = 1,
    wendy_lite_sensorlink_SensorDescriptor_Kind_MICROPHONE = 2,
    wendy_lite_sensorlink_SensorDescriptor_Kind_SENSOR = 3
} wendy_lite_sensorlink_SensorDescriptor_Kind;

/* Struct definitions */
typedef struct _wendy_lite_sensorlink_VideoFormat {
    wendy_lite_sensorlink_VideoFormat_Codec codec;
    uint32_t width;
    uint32_t height;
    uint32_t fps;
} wendy_lite_sensorlink_VideoFormat;

typedef struct _wendy_lite_sensorlink_AudioFormat {
    wendy_lite_sensorlink_AudioFormat_Codec codec;
    uint32_t sample_rate;
    uint32_t channels;
} wendy_lite_sensorlink_AudioFormat;

typedef struct _wendy_lite_sensorlink_SensorFormat {
    pb_callback_t schema; /* type id, e.g. "wendy.imu.v1" */
    uint32_t rate_hz;
    uint32_t sample_bytes;
} wendy_lite_sensorlink_SensorFormat;

typedef struct _wendy_lite_sensorlink_SensorDescriptor {
    uint32_t channel_id;
    wendy_lite_sensorlink_SensorDescriptor_Kind kind;
    pb_callback_t name;
    pb_size_t which_format;
    union {
        wendy_lite_sensorlink_VideoFormat video;
        wendy_lite_sensorlink_AudioFormat audio;
        wendy_lite_sensorlink_SensorFormat sensor;
    } format;
} wendy_lite_sensorlink_SensorDescriptor;

typedef struct _wendy_lite_sensorlink_SensorManifest {
    int32_t device_asset_id;
    pb_size_t sensors_count;
    wendy_lite_sensorlink_SensorDescriptor sensors[16];
} wendy_lite_sensorlink_SensorManifest;

typedef struct _wendy_lite_sensorlink_GetSensorManifest {
    char dummy_field;
} wendy_lite_sensorlink_GetSensorManifest;

typedef struct _wendy_lite_sensorlink_Subscribe {
    pb_size_t channel_id_count;
    uint32_t channel_id[16];
} wendy_lite_sensorlink_Subscribe;

typedef struct _wendy_lite_sensorlink_Unsubscribe {
    pb_size_t channel_id_count;
    uint32_t channel_id[16];
} wendy_lite_sensorlink_Unsubscribe;

typedef struct _wendy_lite_sensorlink_SensorFrame {
    uint32_t channel_id;
    uint32_t seq;
    uint64_t ts_us;
    uint32_t flags; /* bit0 = keyframe */
    pb_callback_t payload;
} wendy_lite_sensorlink_SensorFrame;

typedef struct _wendy_lite_sensorlink_Ping {
    uint64_t ts_us;
} wendy_lite_sensorlink_Ping;

/* Every message on the wire is an Envelope, so framing needs only one type. */
typedef struct _wendy_lite_sensorlink_Envelope {
    pb_size_t which_msg;
    union {
        wendy_lite_sensorlink_SensorManifest manifest;
        wendy_lite_sensorlink_Subscribe subscribe;
        wendy_lite_sensorlink_SensorFrame frame;
        wendy_lite_sensorlink_Ping ping;
    } msg;
} wendy_lite_sensorlink_Envelope;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _wendy_lite_sensorlink_VideoFormat_Codec_MIN wendy_lite_sensorlink_VideoFormat_Codec_CODEC_UNSPECIFIED
#define _wendy_lite_sensorlink_VideoFormat_Codec_MAX wendy_lite_sensorlink_VideoFormat_Codec_H264
#define _wendy_lite_sensorlink_VideoFormat_Codec_ARRAYSIZE ((wendy_lite_sensorlink_VideoFormat_Codec)(wendy_lite_sensorlink_VideoFormat_Codec_H264+1))

#define _wendy_lite_sensorlink_AudioFormat_Codec_MIN wendy_lite_sensorlink_AudioFormat_Codec_CODEC_UNSPECIFIED
#define _wendy_lite_sensorlink_AudioFormat_Codec_MAX wendy_lite_sensorlink_AudioFormat_Codec_OPUS
#define _wendy_lite_sensorlink_AudioFormat_Codec_ARRAYSIZE ((wendy_lite_sensorlink_AudioFormat_Codec)(wendy_lite_sensorlink_AudioFormat_Codec_OPUS+1))

#define _wendy_lite_sensorlink_SensorDescriptor_Kind_MIN wendy_lite_sensorlink_SensorDescriptor_Kind_KIND_UNSPECIFIED
#define _wendy_lite_sensorlink_SensorDescriptor_Kind_MAX wendy_lite_sensorlink_SensorDescriptor_Kind_SENSOR
#define _wendy_lite_sensorlink_SensorDescriptor_Kind_ARRAYSIZE ((wendy_lite_sensorlink_SensorDescriptor_Kind)(wendy_lite_sensorlink_SensorDescriptor_Kind_SENSOR+1))

#define wendy_lite_sensorlink_VideoFormat_codec_ENUMTYPE wendy_lite_sensorlink_VideoFormat_Codec

#define wendy_lite_sensorlink_AudioFormat_codec_ENUMTYPE wendy_lite_sensorlink_AudioFormat_Codec


#define wendy_lite_sensorlink_SensorDescriptor_kind_ENUMTYPE wendy_lite_sensorlink_SensorDescriptor_Kind









/* Initializer values for message structs */
#define wendy_lite_sensorlink_VideoFormat_init_default {_wendy_lite_sensorlink_VideoFormat_Codec_MIN, 0, 0, 0}
#define wendy_lite_sensorlink_AudioFormat_init_default {_wendy_lite_sensorlink_AudioFormat_Codec_MIN, 0, 0}
#define wendy_lite_sensorlink_SensorFormat_init_default {{{NULL}, NULL}, 0, 0}
#define wendy_lite_sensorlink_SensorDescriptor_init_default {0, _wendy_lite_sensorlink_SensorDescriptor_Kind_MIN, {{NULL}, NULL}, 0, {wendy_lite_sensorlink_VideoFormat_init_default}}
#define wendy_lite_sensorlink_SensorManifest_init_default {0, 0, {wendy_lite_sensorlink_SensorDescriptor_init_default, wendy_lite_sensorlink_SensorDescriptor_init_default, wendy_lite_sensorlink_SensorDescriptor_init_default, wendy_lite_sensorlink_SensorDescriptor_init_default, wendy_lite_sensorlink_SensorDescriptor_init_default, wendy_lite_sensorlink_SensorDescriptor_init_default, wendy_lite_sensorlink_SensorDescriptor_init_default, wendy_lite_sensorlink_SensorDescriptor_init_default, wendy_lite_sensorlink_SensorDescriptor_init_default, wendy_lite_sensorlink_SensorDescriptor_init_default, wendy_lite_sensorlink_SensorDescriptor_init_default, wendy_lite_sensorlink_SensorDescriptor_init_default, wendy_lite_sensorlink_SensorDescriptor_init_default, wendy_lite_sensorlink_SensorDescriptor_init_default, wendy_lite_sensorlink_SensorDescriptor_init_default, wendy_lite_sensorlink_SensorDescriptor_init_default}}
#define wendy_lite_sensorlink_GetSensorManifest_init_default {0}
#define wendy_lite_sensorlink_Subscribe_init_default {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define wendy_lite_sensorlink_Unsubscribe_init_default {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define wendy_lite_sensorlink_SensorFrame_init_default {0, 0, 0, 0, {{NULL}, NULL}}
#define wendy_lite_sensorlink_Ping_init_default  {0}
#define wendy_lite_sensorlink_Envelope_init_default {0, {wendy_lite_sensorlink_SensorManifest_init_default}}
#define wendy_lite_sensorlink_VideoFormat_init_zero {_wendy_lite_sensorlink_VideoFormat_Codec_MIN, 0, 0, 0}
#define wendy_lite_sensorlink_AudioFormat_init_zero {_wendy_lite_sensorlink_AudioFormat_Codec_MIN, 0, 0}
#define wendy_lite_sensorlink_SensorFormat_init_zero {{{NULL}, NULL}, 0, 0}
#define wendy_lite_sensorlink_SensorDescriptor_init_zero {0, _wendy_lite_sensorlink_SensorDescriptor_Kind_MIN, {{NULL}, NULL}, 0, {wendy_lite_sensorlink_VideoFormat_init_zero}}
#define wendy_lite_sensorlink_SensorManifest_init_zero {0, 0, {wendy_lite_sensorlink_SensorDescriptor_init_zero, wendy_lite_sensorlink_SensorDescriptor_init_zero, wendy_lite_sensorlink_SensorDescriptor_init_zero, wendy_lite_sensorlink_SensorDescriptor_init_zero, wendy_lite_sensorlink_SensorDescriptor_init_zero, wendy_lite_sensorlink_SensorDescriptor_init_zero, wendy_lite_sensorlink_SensorDescriptor_init_zero, wendy_lite_sensorlink_SensorDescriptor_init_zero, wendy_lite_sensorlink_SensorDescriptor_init_zero, wendy_lite_sensorlink_SensorDescriptor_init_zero, wendy_lite_sensorlink_SensorDescriptor_init_zero, wendy_lite_sensorlink_SensorDescriptor_init_zero, wendy_lite_sensorlink_SensorDescriptor_init_zero, wendy_lite_sensorlink_SensorDescriptor_init_zero, wendy_lite_sensorlink_SensorDescriptor_init_zero, wendy_lite_sensorlink_SensorDescriptor_init_zero}}
#define wendy_lite_sensorlink_GetSensorManifest_init_zero {0}
#define wendy_lite_sensorlink_Subscribe_init_zero {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define wendy_lite_sensorlink_Unsubscribe_init_zero {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define wendy_lite_sensorlink_SensorFrame_init_zero {0, 0, 0, 0, {{NULL}, NULL}}
#define wendy_lite_sensorlink_Ping_init_zero     {0}
#define wendy_lite_sensorlink_Envelope_init_zero {0, {wendy_lite_sensorlink_SensorManifest_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define wendy_lite_sensorlink_VideoFormat_codec_tag 1
#define wendy_lite_sensorlink_VideoFormat_width_tag 2
#define wendy_lite_sensorlink_VideoFormat_height_tag 3
#define wendy_lite_sensorlink_VideoFormat_fps_tag 4
#define wendy_lite_sensorlink_AudioFormat_codec_tag 1
#define wendy_lite_sensorlink_AudioFormat_sample_rate_tag 2
#define wendy_lite_sensorlink_AudioFormat_channels_tag 3
#define wendy_lite_sensorlink_SensorFormat_schema_tag 1
#define wendy_lite_sensorlink_SensorFormat_rate_hz_tag 2
#define wendy_lite_sensorlink_SensorFormat_sample_bytes_tag 3
#define wendy_lite_sensorlink_SensorDescriptor_channel_id_tag 1
#define wendy_lite_sensorlink_SensorDescriptor_kind_tag 2
#define wendy_lite_sensorlink_SensorDescriptor_name_tag 3
#define wendy_lite_sensorlink_SensorDescriptor_video_tag 4
#define wendy_lite_sensorlink_SensorDescriptor_audio_tag 5
#define wendy_lite_sensorlink_SensorDescriptor_sensor_tag 6
#define wendy_lite_sensorlink_SensorManifest_device_asset_id_tag 1
#define wendy_lite_sensorlink_SensorManifest_sensors_tag 2
#define wendy_lite_sensorlink_Subscribe_channel_id_tag 1
#define wendy_lite_sensorlink_Unsubscribe_channel_id_tag 1
#define wendy_lite_sensorlink_SensorFrame_channel_id_tag 1
#define wendy_lite_sensorlink_SensorFrame_seq_tag 2
#define wendy_lite_sensorlink_SensorFrame_ts_us_tag 3
#define wendy_lite_sensorlink_SensorFrame_flags_tag 4
#define wendy_lite_sensorlink_SensorFrame_payload_tag 5
#define wendy_lite_sensorlink_Ping_ts_us_tag     1
#define wendy_lite_sensorlink_Envelope_manifest_tag 1
#define wendy_lite_sensorlink_Envelope_subscribe_tag 2
#define wendy_lite_sensorlink_Envelope_frame_tag 3
#define wendy_lite_sensorlink_Envelope_ping_tag  4

/* Struct field encoding specification for nanopb */
#define wendy_lite_sensorlink_VideoFormat_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    codec,             1) \
X(a, STATIC,   SINGULAR, UINT32,   width,             2) \
X(a, STATIC,   SINGULAR, UINT32,   height,            3) \
X(a, STATIC,   SINGULAR, UINT32,   fps,               4)
#define wendy_lite_sensorlink_VideoFormat_CALLBACK NULL
#define wendy_lite_sensorlink_VideoFormat_DEFAULT NULL

#define wendy_lite_sensorlink_AudioFormat_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    codec,             1) \
X(a, STATIC,   SINGULAR, UINT32,   sample_rate,       2) \
X(a, STATIC,   SINGULAR, UINT32,   channels,          3)
#define wendy_lite_sensorlink_AudioFormat_CALLBACK NULL
#define wendy_lite_sensorlink_AudioFormat_DEFAULT NULL

#define wendy_lite_sensorlink_SensorFormat_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   schema,            1) \
X(a, STATIC,   SINGULAR, UINT32,   rate_hz,           2) \
X(a, STATIC,   SINGULAR, UINT32,   sample_bytes,      3)
#define wendy_lite_sensorlink_SensorFormat_CALLBACK pb_default_field_callback
#define wendy_lite_sensorlink_SensorFormat_DEFAULT NULL

#define wendy_lite_sensorlink_SensorDescriptor_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   channel_id,        1) \
X(a, STATIC,   SINGULAR, UENUM,    kind,              2) \
X(a, CALLBACK, SINGULAR, STRING,   name,              3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (format,video,format.video),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (format,audio,format.audio),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (format,sensor,format.sensor),   6)
#define wendy_lite_sensorlink_SensorDescriptor_CALLBACK pb_default_field_callback
#define wendy_lite_sensorlink_SensorDescriptor_DEFAULT NULL
#define wendy_lite_sensorlink_SensorDescriptor_format_video_MSGTYPE wendy_lite_sensorlink_VideoFormat
#define wendy_lite_sensorlink_SensorDescriptor_format_audio_MSGTYPE wendy_lite_sensorlink_AudioFormat
#define wendy_lite_sensorlink_SensorDescriptor_format_sensor_MSGTYPE wendy_lite_sensorlink_SensorFormat

#define wendy_lite_sensorlink_SensorManifest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    device_asset_id,   1) \
X(a, STATIC,   REPEATED, MESSAGE,  sensors,           2)
#define wendy_lite_sensorlink_SensorManifest_CALLBACK NULL
#define wendy_lite_sensorlink_SensorManifest_DEFAULT NULL
#define wendy_lite_sensorlink_SensorManifest_sensors_MSGTYPE wendy_lite_sensorlink_SensorDescriptor

#define wendy_lite_sensorlink_GetSensorManifest_FIELDLIST(X, a) \

#define wendy_lite_sensorlink_GetSensorManifest_CALLBACK NULL
#define wendy_lite_sensorlink_GetSensorManifest_DEFAULT NULL

#define wendy_lite_sensorlink_Subscribe_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, UINT32,   channel_id,        1)
#define wendy_lite_sensorlink_Subscribe_CALLBACK NULL
#define wendy_lite_sensorlink_Subscribe_DEFAULT NULL

#define wendy_lite_sensorlink_Unsubscribe_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, UINT32,   channel_id,        1)
#define wendy_lite_sensorlink_Unsubscribe_CALLBACK NULL
#define wendy_lite_sensorlink_Unsubscribe_DEFAULT NULL

#define wendy_lite_sensorlink_SensorFrame_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   channel_id,        1) \
X(a, STATIC,   SINGULAR, UINT32,   seq,               2) \
X(a, STATIC,   SINGULAR, UINT64,   ts_us,             3) \
X(a, STATIC,   SINGULAR, UINT32,   flags,             4) \
X(a, CALLBACK, SINGULAR, BYTES,    payload,           5)
#define wendy_lite_sensorlink_SensorFrame_CALLBACK pb_default_field_callback
#define wendy_lite_sensorlink_SensorFrame_DEFAULT NULL

#define wendy_lite_sensorlink_Ping_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   ts_us,             1)
#define wendy_lite_sensorlink_Ping_CALLBACK NULL
#define wendy_lite_sensorlink_Ping_DEFAULT NULL

#define wendy_lite_sensorlink_Envelope_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,manifest,msg.manifest),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,subscribe,msg.subscribe),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,frame,msg.frame),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,ping,msg.ping),   4)
#define wendy_lite_sensorlink_Envelope_CALLBACK NULL
#define wendy_lite_sensorlink_Envelope_DEFAULT NULL
#define wendy_lite_sensorlink_Envelope_msg_manifest_MSGTYPE wendy_lite_sensorlink_SensorManifest
#define wendy_lite_sensorlink_Envelope_msg_subscribe_MSGTYPE wendy_lite_sensorlink_Subscribe
#define wendy_lite_sensorlink_Envelope_msg_frame_MSGTYPE wendy_lite_sensorlink_SensorFrame
#define wendy_lite_sensorlink_Envelope_msg_ping_MSGTYPE wendy_lite_sensorlink_Ping

extern const pb_msgdesc_t wendy_lite_sensorlink_VideoFormat_msg;
extern const pb_msgdesc_t wendy_lite_sensorlink_AudioFormat_msg;
extern const pb_msgdesc_t wendy_lite_sensorlink_SensorFormat_msg;
extern const pb_msgdesc_t wendy_lite_sensorlink_SensorDescriptor_msg;
extern const pb_msgdesc_t wendy_lite_sensorlink_SensorManifest_msg;
extern const pb_msgdesc_t wendy_lite_sensorlink_GetSensorManifest_msg;
extern const pb_msgdesc_t wendy_lite_sensorlink_Subscribe_msg;
extern const pb_msgdesc_t wendy_lite_sensorlink_Unsubscribe_msg;
extern const pb_msgdesc_t wendy_lite_sensorlink_SensorFrame_msg;
extern const pb_msgdesc_t wendy_lite_sensorlink_Ping_msg;
extern const pb_msgdesc_t wendy_lite_sensorlink_Envelope_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define wendy_lite_sensorlink_VideoFormat_fields &wendy_lite_sensorlink_VideoFormat_msg
#define wendy_lite_sensorlink_AudioFormat_fields &wendy_lite_sensorlink_AudioFormat_msg
#define wendy_lite_sensorlink_SensorFormat_fields &wendy_lite_sensorlink_SensorFormat_msg
#define wendy_lite_sensorlink_SensorDescriptor_fields &wendy_lite_sensorlink_SensorDescriptor_msg
#define wendy_lite_sensorlink_SensorManifest_fields &wendy_lite_sensorlink_SensorManifest_msg
#define wendy_lite_sensorlink_GetSensorManifest_fields &wendy_lite_sensorlink_GetSensorManifest_msg
#define wendy_lite_sensorlink_Subscribe_fields &wendy_lite_sensorlink_Subscribe_msg
#define wendy_lite_sensorlink_Unsubscribe_fields &wendy_lite_sensorlink_Unsubscribe_msg
#define wendy_lite_sensorlink_SensorFrame_fields &wendy_lite_sensorlink_SensorFrame_msg
#define wendy_lite_sensorlink_Ping_fields &wendy_lite_sensorlink_Ping_msg
#define wendy_lite_sensorlink_Envelope_fields &wendy_lite_sensorlink_Envelope_msg

/* Maximum encoded size of messages (where known) */
/* wendy_lite_sensorlink_SensorFormat_size depends on runtime parameters */
/* wendy_lite_sensorlink_SensorDescriptor_size depends on runtime parameters */
/* wendy_lite_sensorlink_SensorManifest_size depends on runtime parameters */
/* wendy_lite_sensorlink_SensorFrame_size depends on runtime parameters */
/* wendy_lite_sensorlink_Envelope_size depends on runtime parameters */
#define WENDY_LITE_SENSORLINK_SENSORLINK_PB_H_MAX_SIZE wendy_lite_sensorlink_Subscribe_size
#define wendy_lite_sensorlink_AudioFormat_size   14
#define wendy_lite_sensorlink_GetSensorManifest_size 0
#define wendy_lite_sensorlink_Ping_size          11
#define wendy_lite_sensorlink_Subscribe_size     96
#define wendy_lite_sensorlink_Unsubscribe_size   96
#define wendy_lite_sensorlink_VideoFormat_size   20

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
