/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_WENDY_COM_MSG_PB_H_INCLUDED
#define PB_WENDY_COM_MSG_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _WendyComResult {
    WendyComResult_WENDY_COM_RESULT_OK = 0,
    WendyComResult_WENDY_COM_RESULT_UNKNOWN_ERROR = 1,
    WendyComResult_WENDY_COM_RESULT_BAD_STATE = 2,
    WendyComResult_WENDY_COM_RESULT_BUSY = 3
} WendyComResult;

/* Struct definitions */
/* Response data for WENDY_COM_CMD_GET_PROTOCOL_VERSION */
typedef struct _WendyComProtocolVersion {
    uint32_t major;
    uint32_t minor;
} WendyComProtocolVersion;

/* Command parameter messages — empty ones serve as presence markers. */
typedef struct _WendyComGetProtocolVersionParams {
    char dummy_field;
} WendyComGetProtocolVersionParams;

typedef struct _WendyComPingParams {
    char dummy_field;
} WendyComPingParams;

typedef struct _WendyComRebootParams {
    char dummy_field;
} WendyComRebootParams;

/* Params for WENDY_COM_CMD_APP_PUSH_BEGIN */
typedef struct _WendyComAppPushBeginParams {
    uint32_t size;
} WendyComAppPushBeginParams;

/* Params for WENDY_COM_CMD_APP_PUSH_DATA */
typedef struct _WendyComAppPushDataParams {
    uint32_t offset;
    pb_callback_t data;
} WendyComAppPushDataParams;

typedef struct _WendyComAppPushEndParams {
    char dummy_field;
} WendyComAppPushEndParams;

typedef struct _WendyComAppStartParams {
    char dummy_field;
} WendyComAppStartParams;

typedef struct _WendyComAppStopParams {
    char dummy_field;
} WendyComAppStopParams;

/* Top-level command message — the oneof variant identifies the command. */
typedef struct _WendyComCommand {
    uint32_t request_id;
    pb_size_t which_params;
    union {
        WendyComGetProtocolVersionParams get_protocol_version;
        WendyComPingParams ping;
        WendyComRebootParams reboot;
        WendyComAppPushBeginParams app_push_begin;
        WendyComAppPushDataParams app_push_data;
        WendyComAppPushEndParams app_push_end;
        WendyComAppStartParams app_start;
        WendyComAppStopParams app_stop;
    } params;
} WendyComCommand;

/* Response to a WendyComCommand — request_id matches the request. */
typedef struct _WendyComResponse {
    uint32_t request_id;
    WendyComResult result;
    pb_size_t which_data;
    union {
        WendyComProtocolVersion protocol_version;
    } data;
} WendyComResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _WendyComResult_MIN WendyComResult_WENDY_COM_RESULT_OK
#define _WendyComResult_MAX WendyComResult_WENDY_COM_RESULT_BUSY
#define _WendyComResult_ARRAYSIZE ((WendyComResult)(WendyComResult_WENDY_COM_RESULT_BUSY+1))











#define WendyComResponse_result_ENUMTYPE WendyComResult


/* Initializer values for message structs */
#define WendyComProtocolVersion_init_default     {0, 0}
#define WendyComGetProtocolVersionParams_init_default {0}
#define WendyComPingParams_init_default          {0}
#define WendyComRebootParams_init_default        {0}
#define WendyComAppPushBeginParams_init_default  {0}
#define WendyComAppPushDataParams_init_default   {0, {{NULL}, NULL}}
#define WendyComAppPushEndParams_init_default    {0}
#define WendyComAppStartParams_init_default      {0}
#define WendyComAppStopParams_init_default       {0}
#define WendyComCommand_init_default             {0, 0, {WendyComGetProtocolVersionParams_init_default}}
#define WendyComResponse_init_default            {0, _WendyComResult_MIN, 0, {WendyComProtocolVersion_init_default}}
#define WendyComProtocolVersion_init_zero        {0, 0}
#define WendyComGetProtocolVersionParams_init_zero {0}
#define WendyComPingParams_init_zero             {0}
#define WendyComRebootParams_init_zero           {0}
#define WendyComAppPushBeginParams_init_zero     {0}
#define WendyComAppPushDataParams_init_zero      {0, {{NULL}, NULL}}
#define WendyComAppPushEndParams_init_zero       {0}
#define WendyComAppStartParams_init_zero         {0}
#define WendyComAppStopParams_init_zero          {0}
#define WendyComCommand_init_zero                {0, 0, {WendyComGetProtocolVersionParams_init_zero}}
#define WendyComResponse_init_zero               {0, _WendyComResult_MIN, 0, {WendyComProtocolVersion_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define WendyComProtocolVersion_major_tag        1
#define WendyComProtocolVersion_minor_tag        2
#define WendyComAppPushBeginParams_size_tag      1
#define WendyComAppPushDataParams_offset_tag     1
#define WendyComAppPushDataParams_data_tag       2
#define WendyComCommand_request_id_tag           1
#define WendyComCommand_get_protocol_version_tag 2
#define WendyComCommand_ping_tag                 3
#define WendyComCommand_reboot_tag               4
#define WendyComCommand_app_push_begin_tag       5
#define WendyComCommand_app_push_data_tag        6
#define WendyComCommand_app_push_end_tag         7
#define WendyComCommand_app_start_tag            8
#define WendyComCommand_app_stop_tag             9
#define WendyComResponse_request_id_tag          1
#define WendyComResponse_result_tag              2
#define WendyComResponse_protocol_version_tag    3

/* Struct field encoding specification for nanopb */
#define WendyComProtocolVersion_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   major,             1) \
X(a, STATIC,   SINGULAR, UINT32,   minor,             2)
#define WendyComProtocolVersion_CALLBACK NULL
#define WendyComProtocolVersion_DEFAULT NULL

#define WendyComGetProtocolVersionParams_FIELDLIST(X, a) \

#define WendyComGetProtocolVersionParams_CALLBACK NULL
#define WendyComGetProtocolVersionParams_DEFAULT NULL

#define WendyComPingParams_FIELDLIST(X, a) \

#define WendyComPingParams_CALLBACK NULL
#define WendyComPingParams_DEFAULT NULL

#define WendyComRebootParams_FIELDLIST(X, a) \

#define WendyComRebootParams_CALLBACK NULL
#define WendyComRebootParams_DEFAULT NULL

#define WendyComAppPushBeginParams_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   size,              1)
#define WendyComAppPushBeginParams_CALLBACK NULL
#define WendyComAppPushBeginParams_DEFAULT NULL

#define WendyComAppPushDataParams_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   offset,            1) \
X(a, CALLBACK, SINGULAR, BYTES,    data,              2)
#define WendyComAppPushDataParams_CALLBACK pb_default_field_callback
#define WendyComAppPushDataParams_DEFAULT NULL

#define WendyComAppPushEndParams_FIELDLIST(X, a) \

#define WendyComAppPushEndParams_CALLBACK NULL
#define WendyComAppPushEndParams_DEFAULT NULL

#define WendyComAppStartParams_FIELDLIST(X, a) \

#define WendyComAppStartParams_CALLBACK NULL
#define WendyComAppStartParams_DEFAULT NULL

#define WendyComAppStopParams_FIELDLIST(X, a) \

#define WendyComAppStopParams_CALLBACK NULL
#define WendyComAppStopParams_DEFAULT NULL

#define WendyComCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   request_id,        1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,get_protocol_version,params.get_protocol_version),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,ping,params.ping),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,reboot,params.reboot),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,app_push_begin,params.app_push_begin),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,app_push_data,params.app_push_data),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,app_push_end,params.app_push_end),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,app_start,params.app_start),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,app_stop,params.app_stop),   9)
#define WendyComCommand_CALLBACK NULL
#define WendyComCommand_DEFAULT NULL
#define WendyComCommand_params_get_protocol_version_MSGTYPE WendyComGetProtocolVersionParams
#define WendyComCommand_params_ping_MSGTYPE WendyComPingParams
#define WendyComCommand_params_reboot_MSGTYPE WendyComRebootParams
#define WendyComCommand_params_app_push_begin_MSGTYPE WendyComAppPushBeginParams
#define WendyComCommand_params_app_push_data_MSGTYPE WendyComAppPushDataParams
#define WendyComCommand_params_app_push_end_MSGTYPE WendyComAppPushEndParams
#define WendyComCommand_params_app_start_MSGTYPE WendyComAppStartParams
#define WendyComCommand_params_app_stop_MSGTYPE WendyComAppStopParams

#define WendyComResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   request_id,        1) \
X(a, STATIC,   SINGULAR, UENUM,    result,            2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (data,protocol_version,data.protocol_version),   3)
#define WendyComResponse_CALLBACK NULL
#define WendyComResponse_DEFAULT NULL
#define WendyComResponse_data_protocol_version_MSGTYPE WendyComProtocolVersion

extern const pb_msgdesc_t WendyComProtocolVersion_msg;
extern const pb_msgdesc_t WendyComGetProtocolVersionParams_msg;
extern const pb_msgdesc_t WendyComPingParams_msg;
extern const pb_msgdesc_t WendyComRebootParams_msg;
extern const pb_msgdesc_t WendyComAppPushBeginParams_msg;
extern const pb_msgdesc_t WendyComAppPushDataParams_msg;
extern const pb_msgdesc_t WendyComAppPushEndParams_msg;
extern const pb_msgdesc_t WendyComAppStartParams_msg;
extern const pb_msgdesc_t WendyComAppStopParams_msg;
extern const pb_msgdesc_t WendyComCommand_msg;
extern const pb_msgdesc_t WendyComResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define WendyComProtocolVersion_fields &WendyComProtocolVersion_msg
#define WendyComGetProtocolVersionParams_fields &WendyComGetProtocolVersionParams_msg
#define WendyComPingParams_fields &WendyComPingParams_msg
#define WendyComRebootParams_fields &WendyComRebootParams_msg
#define WendyComAppPushBeginParams_fields &WendyComAppPushBeginParams_msg
#define WendyComAppPushDataParams_fields &WendyComAppPushDataParams_msg
#define WendyComAppPushEndParams_fields &WendyComAppPushEndParams_msg
#define WendyComAppStartParams_fields &WendyComAppStartParams_msg
#define WendyComAppStopParams_fields &WendyComAppStopParams_msg
#define WendyComCommand_fields &WendyComCommand_msg
#define WendyComResponse_fields &WendyComResponse_msg

/* Maximum encoded size of messages (where known) */
/* WendyComAppPushDataParams_size depends on runtime parameters */
/* WendyComCommand_size depends on runtime parameters */
#define WENDY_COM_MSG_PB_H_MAX_SIZE              WendyComResponse_size
#define WendyComAppPushBeginParams_size          6
#define WendyComAppPushEndParams_size            0
#define WendyComAppStartParams_size              0
#define WendyComAppStopParams_size               0
#define WendyComGetProtocolVersionParams_size    0
#define WendyComPingParams_size                  0
#define WendyComProtocolVersion_size             12
#define WendyComRebootParams_size                0
#define WendyComResponse_size                    22

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
