/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_WENDY_COM_MSG_PB_H_INCLUDED
#define PB_WENDY_COM_MSG_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Type of app pushed by WENDY_COM_CMD_APP_PUSH_BEGIN — wasm when omitted. */
typedef enum _WendyComAppType {
    WendyComAppType_WENDY_COM_APP_TYPE_WASM = 0,
    WendyComAppType_WENDY_COM_APP_TYPE_NATIVE = 1
} WendyComAppType;

typedef enum _WendyComResult {
    WendyComResult_WENDY_COM_RESULT_OK = 0,
    WendyComResult_WENDY_COM_RESULT_UNKNOWN_ERROR = 1,
    WendyComResult_WENDY_COM_RESULT_BAD_PROTOCOL_VERSION = 2,
    WendyComResult_WENDY_COM_RESULT_BAD_STATE = 3,
    WendyComResult_WENDY_COM_RESULT_BUSY = 4,
    WendyComResult_WENDY_COM_RESULT_BAD_APP_TYPE = 5,
    WendyComResult_WENDY_COM_RESULT_BAD_APP_SIZE = 6
} WendyComResult;

/* Struct definitions */
/* Response data for WENDY_COM_CMD_GET_PROTOCOL_VERSION */
typedef struct _WendyComProtocolVersion {
    uint32_t major;
    uint32_t minor;
} WendyComProtocolVersion;

/* Command parameter messages — empty ones serve as presence markers. */
typedef struct _WendyComProtocolVersionParams {
    uint32_t major;
    uint32_t minor;
} WendyComProtocolVersionParams;

typedef struct _WendyComPingParams {
    char dummy_field;
} WendyComPingParams;

typedef struct _WendyComRebootParams {
    char dummy_field;
} WendyComRebootParams;

/* Params for WENDY_COM_CMD_APP_PUSH_BEGIN */
typedef struct _WendyComAppPushBeginParams {
    uint32_t size;
    WendyComAppType app_type;
} WendyComAppPushBeginParams;

/* Params for WENDY_COM_CMD_APP_PUSH_DATA */
typedef struct _WendyComAppPushDataParams {
    uint32_t offset;
    pb_callback_t data;
} WendyComAppPushDataParams;

typedef struct _WendyComAppPushEndParams {
    char dummy_field;
} WendyComAppPushEndParams;

typedef struct _WendyComAppStartParams {
    char dummy_field;
} WendyComAppStartParams;

typedef struct _WendyComAppStopParams {
    char dummy_field;
} WendyComAppStopParams;

typedef struct _WendyComGetDeviceIdentityParams {
    char dummy_field;
} WendyComGetDeviceIdentityParams;

typedef struct _WendyComDeviceIdentity {
    pb_callback_t id;
    pb_callback_t name;
    pb_callback_t display_name;
} WendyComDeviceIdentity;

/* Top-level command message — the oneof variant identifies the command. */
typedef struct _WendyComCommand {
    uint32_t request_id;
    pb_size_t which_params;
    union {
        WendyComProtocolVersionParams protocol_version;
        WendyComPingParams ping;
        WendyComRebootParams reboot;
        WendyComAppPushBeginParams app_push_begin;
        WendyComAppPushDataParams app_push_data;
        WendyComAppPushEndParams app_push_end;
        WendyComAppStartParams app_start;
        WendyComAppStopParams app_stop;
        WendyComGetDeviceIdentityParams get_device_identity;
    } params;
} WendyComCommand;

/* Response to a WendyComCommand — request_id matches the request. */
typedef struct _WendyComResponse {
    uint32_t request_id;
    WendyComResult result;
    pb_size_t which_data;
    union {
        WendyComProtocolVersion protocol_version;
        WendyComDeviceIdentity device_identity;
    } data;
} WendyComResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _WendyComAppType_MIN WendyComAppType_WENDY_COM_APP_TYPE_WASM
#define _WendyComAppType_MAX WendyComAppType_WENDY_COM_APP_TYPE_NATIVE
#define _WendyComAppType_ARRAYSIZE ((WendyComAppType)(WendyComAppType_WENDY_COM_APP_TYPE_NATIVE+1))

#define _WendyComResult_MIN WendyComResult_WENDY_COM_RESULT_OK
#define _WendyComResult_MAX WendyComResult_WENDY_COM_RESULT_BAD_APP_SIZE
#define _WendyComResult_ARRAYSIZE ((WendyComResult)(WendyComResult_WENDY_COM_RESULT_BAD_APP_SIZE+1))





#define WendyComAppPushBeginParams_app_type_ENUMTYPE WendyComAppType








#define WendyComResponse_result_ENUMTYPE WendyComResult


/* Initializer values for message structs */
#define WendyComProtocolVersion_init_default     {0, 0}
#define WendyComProtocolVersionParams_init_default {0, 0}
#define WendyComPingParams_init_default          {0}
#define WendyComRebootParams_init_default        {0}
#define WendyComAppPushBeginParams_init_default  {0, _WendyComAppType_MIN}
#define WendyComAppPushDataParams_init_default   {0, {{NULL}, NULL}}
#define WendyComAppPushEndParams_init_default    {0}
#define WendyComAppStartParams_init_default      {0}
#define WendyComAppStopParams_init_default       {0}
#define WendyComGetDeviceIdentityParams_init_default {0}
#define WendyComDeviceIdentity_init_default      {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define WendyComCommand_init_default             {0, 0, {WendyComProtocolVersionParams_init_default}}
#define WendyComResponse_init_default            {0, _WendyComResult_MIN, 0, {WendyComProtocolVersion_init_default}}
#define WendyComProtocolVersion_init_zero        {0, 0}
#define WendyComProtocolVersionParams_init_zero  {0, 0}
#define WendyComPingParams_init_zero             {0}
#define WendyComRebootParams_init_zero           {0}
#define WendyComAppPushBeginParams_init_zero     {0, _WendyComAppType_MIN}
#define WendyComAppPushDataParams_init_zero      {0, {{NULL}, NULL}}
#define WendyComAppPushEndParams_init_zero       {0}
#define WendyComAppStartParams_init_zero         {0}
#define WendyComAppStopParams_init_zero          {0}
#define WendyComGetDeviceIdentityParams_init_zero {0}
#define WendyComDeviceIdentity_init_zero         {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define WendyComCommand_init_zero                {0, 0, {WendyComProtocolVersionParams_init_zero}}
#define WendyComResponse_init_zero               {0, _WendyComResult_MIN, 0, {WendyComProtocolVersion_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define WendyComProtocolVersion_major_tag        1
#define WendyComProtocolVersion_minor_tag        2
#define WendyComProtocolVersionParams_major_tag  1
#define WendyComProtocolVersionParams_minor_tag  2
#define WendyComAppPushBeginParams_size_tag      1
#define WendyComAppPushBeginParams_app_type_tag  2
#define WendyComAppPushDataParams_offset_tag     1
#define WendyComAppPushDataParams_data_tag       2
#define WendyComDeviceIdentity_id_tag            1
#define WendyComDeviceIdentity_name_tag          2
#define WendyComDeviceIdentity_display_name_tag  3
#define WendyComCommand_request_id_tag           1
#define WendyComCommand_protocol_version_tag     2
#define WendyComCommand_ping_tag                 3
#define WendyComCommand_reboot_tag               4
#define WendyComCommand_app_push_begin_tag       5
#define WendyComCommand_app_push_data_tag        6
#define WendyComCommand_app_push_end_tag         7
#define WendyComCommand_app_start_tag            8
#define WendyComCommand_app_stop_tag             9
#define WendyComCommand_get_device_identity_tag  10
#define WendyComResponse_request_id_tag          1
#define WendyComResponse_result_tag              2
#define WendyComResponse_protocol_version_tag    3
#define WendyComResponse_device_identity_tag     4

/* Struct field encoding specification for nanopb */
#define WendyComProtocolVersion_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   major,             1) \
X(a, STATIC,   SINGULAR, UINT32,   minor,             2)
#define WendyComProtocolVersion_CALLBACK NULL
#define WendyComProtocolVersion_DEFAULT NULL

#define WendyComProtocolVersionParams_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   major,             1) \
X(a, STATIC,   SINGULAR, UINT32,   minor,             2)
#define WendyComProtocolVersionParams_CALLBACK NULL
#define WendyComProtocolVersionParams_DEFAULT NULL

#define WendyComPingParams_FIELDLIST(X, a) \

#define WendyComPingParams_CALLBACK NULL
#define WendyComPingParams_DEFAULT NULL

#define WendyComRebootParams_FIELDLIST(X, a) \

#define WendyComRebootParams_CALLBACK NULL
#define WendyComRebootParams_DEFAULT NULL

#define WendyComAppPushBeginParams_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   size,              1) \
X(a, STATIC,   SINGULAR, UENUM,    app_type,          2)
#define WendyComAppPushBeginParams_CALLBACK NULL
#define WendyComAppPushBeginParams_DEFAULT NULL

#define WendyComAppPushDataParams_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   offset,            1) \
X(a, CALLBACK, SINGULAR, BYTES,    data,              2)
#define WendyComAppPushDataParams_CALLBACK pb_default_field_callback
#define WendyComAppPushDataParams_DEFAULT NULL

#define WendyComAppPushEndParams_FIELDLIST(X, a) \

#define WendyComAppPushEndParams_CALLBACK NULL
#define WendyComAppPushEndParams_DEFAULT NULL

#define WendyComAppStartParams_FIELDLIST(X, a) \

#define WendyComAppStartParams_CALLBACK NULL
#define WendyComAppStartParams_DEFAULT NULL

#define WendyComAppStopParams_FIELDLIST(X, a) \

#define WendyComAppStopParams_CALLBACK NULL
#define WendyComAppStopParams_DEFAULT NULL

#define WendyComGetDeviceIdentityParams_FIELDLIST(X, a) \

#define WendyComGetDeviceIdentityParams_CALLBACK NULL
#define WendyComGetDeviceIdentityParams_DEFAULT NULL

#define WendyComDeviceIdentity_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   id,                1) \
X(a, CALLBACK, SINGULAR, STRING,   name,              2) \
X(a, CALLBACK, SINGULAR, STRING,   display_name,      3)
#define WendyComDeviceIdentity_CALLBACK pb_default_field_callback
#define WendyComDeviceIdentity_DEFAULT NULL

#define WendyComCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   request_id,        1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,protocol_version,params.protocol_version),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,ping,params.ping),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,reboot,params.reboot),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,app_push_begin,params.app_push_begin),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,app_push_data,params.app_push_data),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,app_push_end,params.app_push_end),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,app_start,params.app_start),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,app_stop,params.app_stop),   9) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,get_device_identity,params.get_device_identity),  10)
#define WendyComCommand_CALLBACK NULL
#define WendyComCommand_DEFAULT NULL
#define WendyComCommand_params_protocol_version_MSGTYPE WendyComProtocolVersionParams
#define WendyComCommand_params_ping_MSGTYPE WendyComPingParams
#define WendyComCommand_params_reboot_MSGTYPE WendyComRebootParams
#define WendyComCommand_params_app_push_begin_MSGTYPE WendyComAppPushBeginParams
#define WendyComCommand_params_app_push_data_MSGTYPE WendyComAppPushDataParams
#define WendyComCommand_params_app_push_end_MSGTYPE WendyComAppPushEndParams
#define WendyComCommand_params_app_start_MSGTYPE WendyComAppStartParams
#define WendyComCommand_params_app_stop_MSGTYPE WendyComAppStopParams
#define WendyComCommand_params_get_device_identity_MSGTYPE WendyComGetDeviceIdentityParams

#define WendyComResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   request_id,        1) \
X(a, STATIC,   SINGULAR, UENUM,    result,            2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (data,protocol_version,data.protocol_version),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (data,device_identity,data.device_identity),   4)
#define WendyComResponse_CALLBACK NULL
#define WendyComResponse_DEFAULT NULL
#define WendyComResponse_data_protocol_version_MSGTYPE WendyComProtocolVersion
#define WendyComResponse_data_device_identity_MSGTYPE WendyComDeviceIdentity

extern const pb_msgdesc_t WendyComProtocolVersion_msg;
extern const pb_msgdesc_t WendyComProtocolVersionParams_msg;
extern const pb_msgdesc_t WendyComPingParams_msg;
extern const pb_msgdesc_t WendyComRebootParams_msg;
extern const pb_msgdesc_t WendyComAppPushBeginParams_msg;
extern const pb_msgdesc_t WendyComAppPushDataParams_msg;
extern const pb_msgdesc_t WendyComAppPushEndParams_msg;
extern const pb_msgdesc_t WendyComAppStartParams_msg;
extern const pb_msgdesc_t WendyComAppStopParams_msg;
extern const pb_msgdesc_t WendyComGetDeviceIdentityParams_msg;
extern const pb_msgdesc_t WendyComDeviceIdentity_msg;
extern const pb_msgdesc_t WendyComCommand_msg;
extern const pb_msgdesc_t WendyComResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define WendyComProtocolVersion_fields &WendyComProtocolVersion_msg
#define WendyComProtocolVersionParams_fields &WendyComProtocolVersionParams_msg
#define WendyComPingParams_fields &WendyComPingParams_msg
#define WendyComRebootParams_fields &WendyComRebootParams_msg
#define WendyComAppPushBeginParams_fields &WendyComAppPushBeginParams_msg
#define WendyComAppPushDataParams_fields &WendyComAppPushDataParams_msg
#define WendyComAppPushEndParams_fields &WendyComAppPushEndParams_msg
#define WendyComAppStartParams_fields &WendyComAppStartParams_msg
#define WendyComAppStopParams_fields &WendyComAppStopParams_msg
#define WendyComGetDeviceIdentityParams_fields &WendyComGetDeviceIdentityParams_msg
#define WendyComDeviceIdentity_fields &WendyComDeviceIdentity_msg
#define WendyComCommand_fields &WendyComCommand_msg
#define WendyComResponse_fields &WendyComResponse_msg

/* Maximum encoded size of messages (where known) */
/* WendyComAppPushDataParams_size depends on runtime parameters */
/* WendyComDeviceIdentity_size depends on runtime parameters */
/* WendyComCommand_size depends on runtime parameters */
/* WendyComResponse_size depends on runtime parameters */
#define WENDY_COM_MSG_PB_H_MAX_SIZE              WendyComProtocolVersion_size
#define WendyComAppPushBeginParams_size          8
#define WendyComAppPushEndParams_size            0
#define WendyComAppStartParams_size              0
#define WendyComAppStopParams_size               0
#define WendyComGetDeviceIdentityParams_size     0
#define WendyComPingParams_size                  0
#define WendyComProtocolVersionParams_size       12
#define WendyComProtocolVersion_size             12
#define WendyComRebootParams_size                0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
