/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "sensorlink.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(wendy_lite_sensorlink_VideoFormat, wendy_lite_sensorlink_VideoFormat, AUTO)


PB_BIND(wendy_lite_sensorlink_AudioFormat, wendy_lite_sensorlink_AudioFormat, AUTO)


PB_BIND(wendy_lite_sensorlink_SensorFormat, wendy_lite_sensorlink_SensorFormat, AUTO)


PB_BIND(wendy_lite_sensorlink_SensorDescriptor, wendy_lite_sensorlink_SensorDescriptor, AUTO)


PB_BIND(wendy_lite_sensorlink_SensorManifest, wendy_lite_sensorlink_SensorManifest, 2)


PB_BIND(wendy_lite_sensorlink_GetSensorManifest, wendy_lite_sensorlink_GetSensorManifest, AUTO)


PB_BIND(wendy_lite_sensorlink_Subscribe, wendy_lite_sensorlink_Subscribe, AUTO)


PB_BIND(wendy_lite_sensorlink_Unsubscribe, wendy_lite_sensorlink_Unsubscribe, AUTO)


PB_BIND(wendy_lite_sensorlink_SensorFrame, wendy_lite_sensorlink_SensorFrame, AUTO)


PB_BIND(wendy_lite_sensorlink_Ping, wendy_lite_sensorlink_Ping, AUTO)


PB_BIND(wendy_lite_sensorlink_Envelope, wendy_lite_sensorlink_Envelope, 2)









