/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "wendy_com_msg.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(WendyComProtocolVersion, WendyComProtocolVersion, AUTO)


PB_BIND(WendyComHandshake, WendyComHandshake, AUTO)


PB_BIND(WendyComPingParams, WendyComPingParams, AUTO)


PB_BIND(WendyComRebootParams, WendyComRebootParams, AUTO)


PB_BIND(WendyComAppPushBeginParams, WendyComAppPushBeginParams, AUTO)


PB_BIND(WendyComAppPushDataParams, WendyComAppPushDataParams, AUTO)


PB_BIND(WendyComAppPushEndParams, WendyComAppPushEndParams, AUTO)


PB_BIND(WendyComAppStartParams, WendyComAppStartParams, AUTO)


PB_BIND(WendyComAppStopParams, WendyComAppStopParams, AUTO)


PB_BIND(WendyComGetDeviceIdentityParams, WendyComGetDeviceIdentityParams, AUTO)


PB_BIND(WendyComDeviceIdentity, WendyComDeviceIdentity, AUTO)


PB_BIND(WendyComGetDeviceInfoParams, WendyComGetDeviceInfoParams, AUTO)


PB_BIND(WendyComDeviceInfo, WendyComDeviceInfo, AUTO)


PB_BIND(WendyComCommand, WendyComCommand, AUTO)


PB_BIND(WendyComResponse, WendyComResponse, AUTO)


PB_BIND(WendyComEvent, WendyComEvent, AUTO)


PB_BIND(WendyComMessage, WendyComMessage, AUTO)







