// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: wendy_com_msg.proto

package wendypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Type of app pushed by WENDY_COM_CMD_APP_PUSH_BEGIN — wasm when omitted.
type WendyComAppType int32

const (
	WendyComAppType_WENDY_COM_APP_TYPE_WASM   WendyComAppType = 0
	WendyComAppType_WENDY_COM_APP_TYPE_NATIVE WendyComAppType = 1
)

// Enum value maps for WendyComAppType.
var (
	WendyComAppType_name = map[int32]string{
		0: "WENDY_COM_APP_TYPE_WASM",
		1: "WENDY_COM_APP_TYPE_NATIVE",
	}
	WendyComAppType_value = map[string]int32{
		"WENDY_COM_APP_TYPE_WASM":   0,
		"WENDY_COM_APP_TYPE_NATIVE": 1,
	}
)

func (x WendyComAppType) Enum() *WendyComAppType {
	p := new(WendyComAppType)
	*p = x
	return p
}

func (x WendyComAppType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WendyComAppType) Descriptor() protoreflect.EnumDescriptor {
	return file_wendy_com_msg_proto_enumTypes[0].Descriptor()
}

func (WendyComAppType) Type() protoreflect.EnumType {
	return &file_wendy_com_msg_proto_enumTypes[0]
}

func (x WendyComAppType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WendyComAppType.Descriptor instead.
func (WendyComAppType) EnumDescriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{0}
}

// Mode of the conf push started by WENDY_COM_CMD_CONF_PUSH_BEGIN — replace
// when omitted. REPLACE makes the pushed blob the whole configuration; UPDATE
// keeps the current value of root fields absent from the pushed blob.
type WendyComConfPushMode int32

const (
	WendyComConfPushMode_WENDY_COM_CONF_PUSH_MODE_REPLACE WendyComConfPushMode = 0
	WendyComConfPushMode_WENDY_COM_CONF_PUSH_MODE_UPDATE  WendyComConfPushMode = 1
)

// Enum value maps for WendyComConfPushMode.
var (
	WendyComConfPushMode_name = map[int32]string{
		0: "WENDY_COM_CONF_PUSH_MODE_REPLACE",
		1: "WENDY_COM_CONF_PUSH_MODE_UPDATE",
	}
	WendyComConfPushMode_value = map[string]int32{
		"WENDY_COM_CONF_PUSH_MODE_REPLACE": 0,
		"WENDY_COM_CONF_PUSH_MODE_UPDATE":  1,
	}
)

func (x WendyComConfPushMode) Enum() *WendyComConfPushMode {
	p := new(WendyComConfPushMode)
	*p = x
	return p
}

func (x WendyComConfPushMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WendyComConfPushMode) Descriptor() protoreflect.EnumDescriptor {
	return file_wendy_com_msg_proto_enumTypes[1].Descriptor()
}

func (WendyComConfPushMode) Type() protoreflect.EnumType {
	return &file_wendy_com_msg_proto_enumTypes[1]
}

func (x WendyComConfPushMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WendyComConfPushMode.Descriptor instead.
func (WendyComConfPushMode) EnumDescriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{1}
}

type WendyComConsoleIo int32

const (
	WendyComConsoleIo_WENDY_COM_CONSOLE_IO_STANDARD_INPUT  WendyComConsoleIo = 0
	WendyComConsoleIo_WENDY_COM_CONSOLE_IO_STANDARD_OUTPUT WendyComConsoleIo = 1
	WendyComConsoleIo_WENDY_COM_CONSOLE_IO_STANDARD_ERROR  WendyComConsoleIo = 2
)

// Enum value maps for WendyComConsoleIo.
var (
	WendyComConsoleIo_name = map[int32]string{
		0: "WENDY_COM_CONSOLE_IO_STANDARD_INPUT",
		1: "WENDY_COM_CONSOLE_IO_STANDARD_OUTPUT",
		2: "WENDY_COM_CONSOLE_IO_STANDARD_ERROR",
	}
	WendyComConsoleIo_value = map[string]int32{
		"WENDY_COM_CONSOLE_IO_STANDARD_INPUT":  0,
		"WENDY_COM_CONSOLE_IO_STANDARD_OUTPUT": 1,
		"WENDY_COM_CONSOLE_IO_STANDARD_ERROR":  2,
	}
)

func (x WendyComConsoleIo) Enum() *WendyComConsoleIo {
	p := new(WendyComConsoleIo)
	*p = x
	return p
}

func (x WendyComConsoleIo) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WendyComConsoleIo) Descriptor() protoreflect.EnumDescriptor {
	return file_wendy_com_msg_proto_enumTypes[2].Descriptor()
}

func (WendyComConsoleIo) Type() protoreflect.EnumType {
	return &file_wendy_com_msg_proto_enumTypes[2]
}

func (x WendyComConsoleIo) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WendyComConsoleIo.Descriptor instead.
func (WendyComConsoleIo) EnumDescriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{2}
}

type WendyComResult int32

const (
	WendyComResult_WENDY_COM_RESULT_OK                   WendyComResult = 0
	WendyComResult_WENDY_COM_RESULT_UNKNOWN_ERROR        WendyComResult = 1
	WendyComResult_WENDY_COM_RESULT_BAD_PROTOCOL_VERSION WendyComResult = 2
	WendyComResult_WENDY_COM_RESULT_BAD_STATE            WendyComResult = 3
	WendyComResult_WENDY_COM_RESULT_BUSY                 WendyComResult = 4
	WendyComResult_WENDY_COM_RESULT_BAD_APP_TYPE         WendyComResult = 5
	WendyComResult_WENDY_COM_RESULT_BAD_APP_SIZE         WendyComResult = 6
	WendyComResult_WENDY_COM_RESULT_BAD_CONF_SIZE        WendyComResult = 7
)

// Enum value maps for WendyComResult.
var (
	WendyComResult_name = map[int32]string{
		0: "WENDY_COM_RESULT_OK",
		1: "WENDY_COM_RESULT_UNKNOWN_ERROR",
		2: "WENDY_COM_RESULT_BAD_PROTOCOL_VERSION",
		3: "WENDY_COM_RESULT_BAD_STATE",
		4: "WENDY_COM_RESULT_BUSY",
		5: "WENDY_COM_RESULT_BAD_APP_TYPE",
		6: "WENDY_COM_RESULT_BAD_APP_SIZE",
		7: "WENDY_COM_RESULT_BAD_CONF_SIZE",
	}
	WendyComResult_value = map[string]int32{
		"WENDY_COM_RESULT_OK":                   0,
		"WENDY_COM_RESULT_UNKNOWN_ERROR":        1,
		"WENDY_COM_RESULT_BAD_PROTOCOL_VERSION": 2,
		"WENDY_COM_RESULT_BAD_STATE":            3,
		"WENDY_COM_RESULT_BUSY":                 4,
		"WENDY_COM_RESULT_BAD_APP_TYPE":         5,
		"WENDY_COM_RESULT_BAD_APP_SIZE":         6,
		"WENDY_COM_RESULT_BAD_CONF_SIZE":        7,
	}
)

func (x WendyComResult) Enum() *WendyComResult {
	p := new(WendyComResult)
	*p = x
	return p
}

func (x WendyComResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WendyComResult) Descriptor() protoreflect.EnumDescriptor {
	return file_wendy_com_msg_proto_enumTypes[3].Descriptor()
}

func (WendyComResult) Type() protoreflect.EnumType {
	return &file_wendy_com_msg_proto_enumTypes[3]
}

func (x WendyComResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WendyComResult.Descriptor instead.
func (WendyComResult) EnumDescriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{3}
}

type WendyComChannelErrorReason int32

const (
	WendyComChannelErrorReason_WENDY_COM_CHANNEL_ERROR_REASON_NOT_OPEN WendyComChannelErrorReason = 0 // command received on a channel that is not open
	WendyComChannelErrorReason_WENDY_COM_CHANNEL_ERROR_REASON_REJECTED WendyComChannelErrorReason = 1 // service message not allowed (open/close refused)
)

// Enum value maps for WendyComChannelErrorReason.
var (
	WendyComChannelErrorReason_name = map[int32]string{
		0: "WENDY_COM_CHANNEL_ERROR_REASON_NOT_OPEN",
		1: "WENDY_COM_CHANNEL_ERROR_REASON_REJECTED",
	}
	WendyComChannelErrorReason_value = map[string]int32{
		"WENDY_COM_CHANNEL_ERROR_REASON_NOT_OPEN": 0,
		"WENDY_COM_CHANNEL_ERROR_REASON_REJECTED": 1,
	}
)

func (x WendyComChannelErrorReason) Enum() *WendyComChannelErrorReason {
	p := new(WendyComChannelErrorReason)
	*p = x
	return p
}

func (x WendyComChannelErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WendyComChannelErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_wendy_com_msg_proto_enumTypes[4].Descriptor()
}

func (WendyComChannelErrorReason) Type() protoreflect.EnumType {
	return &file_wendy_com_msg_proto_enumTypes[4]
}

func (x WendyComChannelErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WendyComChannelErrorReason.Descriptor instead.
func (WendyComChannelErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{4}
}

// Protocol version, exchanged in the handshake. The major number must match
// on both sides; minor is informational.
type WendyComProtocolVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Major         uint32                 `protobuf:"varint,1,opt,name=major,proto3" json:"major,omitempty"`
	Minor         uint32                 `protobuf:"varint,2,opt,name=minor,proto3" json:"minor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComProtocolVersion) Reset() {
	*x = WendyComProtocolVersion{}
	mi := &file_wendy_com_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComProtocolVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComProtocolVersion) ProtoMessage() {}

func (x *WendyComProtocolVersion) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComProtocolVersion.ProtoReflect.Descriptor instead.
func (*WendyComProtocolVersion) Descriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{0}
}

func (x *WendyComProtocolVersion) GetMajor() uint32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *WendyComProtocolVersion) GetMinor() uint32 {
	if x != nil {
		return x.Minor
	}
	return 0
}

// First message in each direction after connect. The host sends its version
// with a fresh handshake_id; the device echoes handshake_id with its own
// version, then eventually closes the connection if the host's major version
// is unsupported. Commands are rejected until the handshake completes.
type WendyComHandshake struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	HandshakeId   uint32                   `protobuf:"varint,1,opt,name=handshake_id,json=handshakeId,proto3" json:"handshake_id,omitempty"`
	Version       *WendyComProtocolVersion `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComHandshake) Reset() {
	*x = WendyComHandshake{}
	mi := &file_wendy_com_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComHandshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComHandshake) ProtoMessage() {}

func (x *WendyComHandshake) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComHandshake.ProtoReflect.Descriptor instead.
func (*WendyComHandshake) Descriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{1}
}

func (x *WendyComHandshake) GetHandshakeId() uint32 {
	if x != nil {
		return x.HandshakeId
	}
	return 0
}

func (x *WendyComHandshake) GetVersion() *WendyComProtocolVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

// Command parameter messages — empty ones serve as presence markers.
type WendyComPingParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComPingParams) Reset() {
	*x = WendyComPingParams{}
	mi := &file_wendy_com_msg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComPingParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComPingParams) ProtoMessage() {}

func (x *WendyComPingParams) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_msg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComPingParams.ProtoReflect.Descriptor instead.
func (*WendyComPingParams) Descriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{2}
}

// Params for WENDY_COM_CMD_REBOOT. app_auto_start defaults to true when
// absent. Settings survive exactly one software reboot; a hardware boot
// resets to defaults. The delay is measured from the end of device init;
// an AppStart command received during the delay starts the app immediately.
type WendyComRebootParams struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AppAutoStart      *bool                  `protobuf:"varint,1,opt,name=app_auto_start,json=appAutoStart,proto3,oneof" json:"app_auto_start,omitempty"`            // absent => true
	AppAutoStartDelay uint32                 `protobuf:"varint,2,opt,name=app_auto_start_delay,json=appAutoStartDelay,proto3" json:"app_auto_start_delay,omitempty"` // milliseconds
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WendyComRebootParams) Reset() {
	*x = WendyComRebootParams{}
	mi := &file_wendy_com_msg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComRebootParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComRebootParams) ProtoMessage() {}

func (x *WendyComRebootParams) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_msg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComRebootParams.ProtoReflect.Descriptor instead.
func (*WendyComRebootParams) Descriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{3}
}

func (x *WendyComRebootParams) GetAppAutoStart() bool {
	if x != nil && x.AppAutoStart != nil {
		return *x.AppAutoStart
	}
	return false
}

func (x *WendyComRebootParams) GetAppAutoStartDelay() uint32 {
	if x != nil {
		return x.AppAutoStartDelay
	}
	return 0
}

// Params for WENDY_COM_CMD_APP_PUSH_BEGIN
type WendyComAppPushBeginParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          uint32                 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	AppType       WendyComAppType        `protobuf:"varint,2,opt,name=app_type,json=appType,proto3,enum=WendyComAppType" json:"app_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComAppPushBeginParams) Reset() {
	*x = WendyComAppPushBeginParams{}
	mi := &file_wendy_com_msg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComAppPushBeginParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComAppPushBeginParams) ProtoMessage() {}

func (x *WendyComAppPushBeginParams) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_msg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComAppPushBeginParams.ProtoReflect.Descriptor instead.
func (*WendyComAppPushBeginParams) Descriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{4}
}

func (x *WendyComAppPushBeginParams) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *WendyComAppPushBeginParams) GetAppType() WendyComAppType {
	if x != nil {
		return x.AppType
	}
	return WendyComAppType_WENDY_COM_APP_TYPE_WASM
}

// Params for WENDY_COM_CMD_APP_PUSH_DATA
type WendyComAppPushDataParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint32                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComAppPushDataParams) Reset() {
	*x = WendyComAppPushDataParams{}
	mi := &file_wendy_com_msg_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComAppPushDataParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComAppPushDataParams) ProtoMessage() {}

func (x *WendyComAppPushDataParams) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_msg_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComAppPushDataParams.ProtoReflect.Descriptor instead.
func (*WendyComAppPushDataParams) Descriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{5}
}

func (x *WendyComAppPushDataParams) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *WendyComAppPushDataParams) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WendyComAppPushEndParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComAppPushEndParams) Reset() {
	*x = WendyComAppPushEndParams{}
	mi := &file_wendy_com_msg_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComAppPushEndParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComAppPushEndParams) ProtoMessage() {}

func (x *WendyComAppPushEndParams) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_msg_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComAppPushEndParams.ProtoReflect.Descriptor instead.
func (*WendyComAppPushEndParams) Descriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{6}
}

type WendyComAppStartParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComAppStartParams) Reset() {
	*x = WendyComAppStartParams{}
	mi := &file_wendy_com_msg_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComAppStartParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComAppStartParams) ProtoMessage() {}

func (x *WendyComAppStartParams) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_msg_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComAppStartParams.ProtoReflect.Descriptor instead.
func (*WendyComAppStartParams) Descriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{7}
}

type WendyComAppStopParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComAppStopParams) Reset() {
	*x = WendyComAppStopParams{}
	mi := &file_wendy_com_msg_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComAppStopParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComAppStopParams) ProtoMessage() {}

func (x *WendyComAppStopParams) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_msg_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComAppStopParams.ProtoReflect.Descriptor instead.
func (*WendyComAppStopParams) Descriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{8}
}

// Params for WENDY_COM_CMD_CONF_PUSH_BEGIN
type WendyComConfPushBeginParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          uint32                 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"` // total size of the encoded WendyConf blob
	Mode          WendyComConfPushMode   `protobuf:"varint,2,opt,name=mode,proto3,enum=WendyComConfPushMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComConfPushBeginParams) Reset() {
	*x = WendyComConfPushBeginParams{}
	mi := &file_wendy_com_msg_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComConfPushBeginParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComConfPushBeginParams) ProtoMessage() {}

func (x *WendyComConfPushBeginParams) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_msg_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComConfPushBeginParams.ProtoReflect.Descriptor instead.
func (*WendyComConfPushBeginParams) Descriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{9}
}

func (x *WendyComConfPushBeginParams) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *WendyComConfPushBeginParams) GetMode() WendyComConfPushMode {
	if x != nil {
		return x.Mode
	}
	return WendyComConfPushMode_WENDY_COM_CONF_PUSH_MODE_REPLACE
}

// Params for WENDY_COM_CMD_CONF_PUSH_DATA
type WendyComConfPushDataParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint32                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComConfPushDataParams) Reset() {
	*x = WendyComConfPushDataParams{}
	mi := &file_wendy_com_msg_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComConfPushDataParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComConfPushDataParams) ProtoMessage() {}

func (x *WendyComConfPushDataParams) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_msg_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComConfPushDataParams.ProtoReflect.Descriptor instead.
func (*WendyComConfPushDataParams) Descriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{10}
}

func (x *WendyComConfPushDataParams) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *WendyComConfPushDataParams) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WendyComConfPushEndParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComConfPushEndParams) Reset() {
	*x = WendyComConfPushEndParams{}
	mi := &file_wendy_com_msg_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComConfPushEndParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComConfPushEndParams) ProtoMessage() {}

func (x *WendyComConfPushEndParams) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_msg_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComConfPushEndParams.ProtoReflect.Descriptor instead.
func (*WendyComConfPushEndParams) Descriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{11}
}

type WendyComGetDeviceIdentityParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComGetDeviceIdentityParams) Reset() {
	*x = WendyComGetDeviceIdentityParams{}
	mi := &file_wendy_com_msg_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComGetDeviceIdentityParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComGetDeviceIdentityParams) ProtoMessage() {}

func (x *WendyComGetDeviceIdentityParams) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_msg_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComGetDeviceIdentityParams.ProtoReflect.Descriptor instead.
func (*WendyComGetDeviceIdentityParams) Descriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{12}
}

type WendyComDeviceIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComDeviceIdentity) Reset() {
	*x = WendyComDeviceIdentity{}
	mi := &file_wendy_com_msg_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComDeviceIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComDeviceIdentity) ProtoMessage() {}

func (x *WendyComDeviceIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_msg_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComDeviceIdentity.ProtoReflect.Descriptor instead.
func (*WendyComDeviceIdentity) Descriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{13}
}

func (x *WendyComDeviceIdentity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WendyComDeviceIdentity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WendyComDeviceIdentity) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type WendyComGetDeviceInfoParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComGetDeviceInfoParams) Reset() {
	*x = WendyComGetDeviceInfoParams{}
	mi := &file_wendy_com_msg_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComGetDeviceInfoParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComGetDeviceInfoParams) ProtoMessage() {}

func (x *WendyComGetDeviceInfoParams) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_msg_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComGetDeviceInfoParams.ProtoReflect.Descriptor instead.
func (*WendyComGetDeviceInfoParams) Descriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{14}
}

// Params for WENDY_COM_CMD_CONSOLE_ATTACH — start streaming console output as
// WendyComConsoleData events carrying the given event_id. A repeated attach
// with the same event_id refreshes the auto-detach deadline.
type WendyComConsoleAttachParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       uint32                 `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Duration      uint32                 `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"` // milliseconds; 0 = no deadline (attach forever)
	Blocking      bool                   `protobuf:"varint,3,opt,name=blocking,proto3" json:"blocking,omitempty"` // writers block when the capture buffer is full, instead of overwriting oldest data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComConsoleAttachParams) Reset() {
	*x = WendyComConsoleAttachParams{}
	mi := &file_wendy_com_msg_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComConsoleAttachParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComConsoleAttachParams) ProtoMessage() {}

func (x *WendyComConsoleAttachParams) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_msg_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComConsoleAttachParams.ProtoReflect.Descriptor instead.
func (*WendyComConsoleAttachParams) Descriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{15}
}

func (x *WendyComConsoleAttachParams) GetEventId() uint32 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *WendyComConsoleAttachParams) GetDuration() uint32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *WendyComConsoleAttachParams) GetBlocking() bool {
	if x != nil {
		return x.Blocking
	}
	return false
}

// Params for WENDY_COM_CMD_CONSOLE_DETACH — stop streaming console output.
type WendyComConsoleDetachParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       uint32                 `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComConsoleDetachParams) Reset() {
	*x = WendyComConsoleDetachParams{}
	mi := &file_wendy_com_msg_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComConsoleDetachParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComConsoleDetachParams) ProtoMessage() {}

func (x *WendyComConsoleDetachParams) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_msg_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComConsoleDetachParams.ProtoReflect.Descriptor instead.
func (*WendyComConsoleDetachParams) Descriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{16}
}

func (x *WendyComConsoleDetachParams) GetEventId() uint32 {
	if x != nil {
		return x.EventId
	}
	return 0
}

// Marks the start of a console stream, sent before the first
// WendyComConsoleData event. Not implemented yet.
type WendyComConsoleBegin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComConsoleBegin) Reset() {
	*x = WendyComConsoleBegin{}
	mi := &file_wendy_com_msg_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComConsoleBegin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComConsoleBegin) ProtoMessage() {}

func (x *WendyComConsoleBegin) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_msg_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComConsoleBegin.ProtoReflect.Descriptor instead.
func (*WendyComConsoleBegin) Descriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{17}
}

// One chunk of console output, streamed as an event while attached.
type WendyComConsoleData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Io            WendyComConsoleIo      `protobuf:"varint,1,opt,name=io,proto3,enum=WendyComConsoleIo" json:"io,omitempty"`
	Gap           bool                   `protobuf:"varint,2,opt,name=gap,proto3" json:"gap,omitempty"` // data was lost before this chunk
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComConsoleData) Reset() {
	*x = WendyComConsoleData{}
	mi := &file_wendy_com_msg_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComConsoleData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComConsoleData) ProtoMessage() {}

func (x *WendyComConsoleData) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_msg_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComConsoleData.ProtoReflect.Descriptor instead.
func (*WendyComConsoleData) Descriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{18}
}

func (x *WendyComConsoleData) GetIo() WendyComConsoleIo {
	if x != nil {
		return x.Io
	}
	return WendyComConsoleIo_WENDY_COM_CONSOLE_IO_STANDARD_INPUT
}

func (x *WendyComConsoleData) GetGap() bool {
	if x != nil {
		return x.Gap
	}
	return false
}

func (x *WendyComConsoleData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Marks the end of a console stream, sent after the last
// WendyComConsoleData event. Not implemented yet.
type WendyComConsoleEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComConsoleEnd) Reset() {
	*x = WendyComConsoleEnd{}
	mi := &file_wendy_com_msg_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComConsoleEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComConsoleEnd) ProtoMessage() {}

func (x *WendyComConsoleEnd) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_msg_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComConsoleEnd.ProtoReflect.Descriptor instead.
func (*WendyComConsoleEnd) Descriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{19}
}

type WendyComDeviceInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Os              string                 `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"` // typically "wendy-lite"
	OsVersion       string                 `protobuf:"bytes,2,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	CpuArchitecture string                 `protobuf:"bytes,3,opt,name=cpu_architecture,json=cpuArchitecture,proto3" json:"cpu_architecture,omitempty"`
	// SoC name, e.g. "esp32c6" or "esp32s3".
	Target           string `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	WasmAppSupport   bool   `protobuf:"varint,5,opt,name=wasm_app_support,json=wasmAppSupport,proto3" json:"wasm_app_support,omitempty"`
	NativeAppSupport bool   `protobuf:"varint,6,opt,name=native_app_support,json=nativeAppSupport,proto3" json:"native_app_support,omitempty"`
	// Board identifier, e.g. "esp32c6_generic" or "esp32s3_seeed_xiao_native".
	// Empty when the board is not known, which is typically the case when
	// wendy-lite is compiled and flashed manually.
	Board         string `protobuf:"bytes,7,opt,name=board,proto3" json:"board,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComDeviceInfo) Reset() {
	*x = WendyComDeviceInfo{}
	mi := &file_wendy_com_msg_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComDeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComDeviceInfo) ProtoMessage() {}

func (x *WendyComDeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_msg_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComDeviceInfo.ProtoReflect.Descriptor instead.
func (*WendyComDeviceInfo) Descriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{20}
}

func (x *WendyComDeviceInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *WendyComDeviceInfo) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *WendyComDeviceInfo) GetCpuArchitecture() string {
	if x != nil {
		return x.CpuArchitecture
	}
	return ""
}

func (x *WendyComDeviceInfo) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *WendyComDeviceInfo) GetWasmAppSupport() bool {
	if x != nil {
		return x.WasmAppSupport
	}
	return false
}

func (x *WendyComDeviceInfo) GetNativeAppSupport() bool {
	if x != nil {
		return x.NativeAppSupport
	}
	return false
}

func (x *WendyComDeviceInfo) GetBoard() string {
	if x != nil {
		return x.Board
	}
	return ""
}

// Command sent host -> device — the oneof variant identifies the command.
type WendyComCommand struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId uint32                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Params:
	//
	//	*WendyComCommand_Ping
	//	*WendyComCommand_Reboot
	//	*WendyComCommand_AppPushBegin
	//	*WendyComCommand_AppPushData
	//	*WendyComCommand_AppPushEnd
	//	*WendyComCommand_AppStart
	//	*WendyComCommand_AppStop
	//	*WendyComCommand_GetDeviceIdentity
	//	*WendyComCommand_GetDeviceInfo
	//	*WendyComCommand_ConsoleAttach
	//	*WendyComCommand_ConsoleDetach
	//	*WendyComCommand_ConfPushBegin
	//	*WendyComCommand_ConfPushData
	//	*WendyComCommand_ConfPushEnd
	Params        isWendyComCommand_Params `protobuf_oneof:"params"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComCommand) Reset() {
	*x = WendyComCommand{}
	mi := &file_wendy_com_msg_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComCommand) ProtoMessage() {}

func (x *WendyComCommand) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_msg_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComCommand.ProtoReflect.Descriptor instead.
func (*WendyComCommand) Descriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{21}
}

func (x *WendyComCommand) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *WendyComCommand) GetParams() isWendyComCommand_Params {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *WendyComCommand) GetPing() *WendyComPingParams {
	if x != nil {
		if x, ok := x.Params.(*WendyComCommand_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *WendyComCommand) GetReboot() *WendyComRebootParams {
	if x != nil {
		if x, ok := x.Params.(*WendyComCommand_Reboot); ok {
			return x.Reboot
		}
	}
	return nil
}

func (x *WendyComCommand) GetAppPushBegin() *WendyComAppPushBeginParams {
	if x != nil {
		if x, ok := x.Params.(*WendyComCommand_AppPushBegin); ok {
			return x.AppPushBegin
		}
	}
	return nil
}

func (x *WendyComCommand) GetAppPushData() *WendyComAppPushDataParams {
	if x != nil {
		if x, ok := x.Params.(*WendyComCommand_AppPushData); ok {
			return x.AppPushData
		}
	}
	return nil
}

func (x *WendyComCommand) GetAppPushEnd() *WendyComAppPushEndParams {
	if x != nil {
		if x, ok := x.Params.(*WendyComCommand_AppPushEnd); ok {
			return x.AppPushEnd
		}
	}
	return nil
}

func (x *WendyComCommand) GetAppStart() *WendyComAppStartParams {
	if x != nil {
		if x, ok := x.Params.(*WendyComCommand_AppStart); ok {
			return x.AppStart
		}
	}
	return nil
}

func (x *WendyComCommand) GetAppStop() *WendyComAppStopParams {
	if x != nil {
		if x, ok := x.Params.(*WendyComCommand_AppStop); ok {
			return x.AppStop
		}
	}
	return nil
}

func (x *WendyComCommand) GetGetDeviceIdentity() *WendyComGetDeviceIdentityParams {
	if x != nil {
		if x, ok := x.Params.(*WendyComCommand_GetDeviceIdentity); ok {
			return x.GetDeviceIdentity
		}
	}
	return nil
}

func (x *WendyComCommand) GetGetDeviceInfo() *WendyComGetDeviceInfoParams {
	if x != nil {
		if x, ok := x.Params.(*WendyComCommand_GetDeviceInfo); ok {
			return x.GetDeviceInfo
		}
	}
	return nil
}

func (x *WendyComCommand) GetConsoleAttach() *WendyComConsoleAttachParams {
	if x != nil {
		if x, ok := x.Params.(*WendyComCommand_ConsoleAttach); ok {
			return x.ConsoleAttach
		}
	}
	return nil
}

func (x *WendyComCommand) GetConsoleDetach() *WendyComConsoleDetachParams {
	if x != nil {
		if x, ok := x.Params.(*WendyComCommand_ConsoleDetach); ok {
			return x.ConsoleDetach
		}
	}
	return nil
}

func (x *WendyComCommand) GetConfPushBegin() *WendyComConfPushBeginParams {
	if x != nil {
		if x, ok := x.Params.(*WendyComCommand_ConfPushBegin); ok {
			return x.ConfPushBegin
		}
	}
	return nil
}

func (x *WendyComCommand) GetConfPushData() *WendyComConfPushDataParams {
	if x != nil {
		if x, ok := x.Params.(*WendyComCommand_ConfPushData); ok {
			return x.ConfPushData
		}
	}
	return nil
}

func (x *WendyComCommand) GetConfPushEnd() *WendyComConfPushEndParams {
	if x != nil {
		if x, ok := x.Params.(*WendyComCommand_ConfPushEnd); ok {
			return x.ConfPushEnd
		}
	}
	return nil
}

type isWendyComCommand_Params interface {
	isWendyComCommand_Params()
}

type WendyComCommand_Ping struct {
	Ping *WendyComPingParams `protobuf:"bytes,2,opt,name=ping,proto3,oneof"`
}

type WendyComCommand_Reboot struct {
	Reboot *WendyComRebootParams `protobuf:"bytes,3,opt,name=reboot,proto3,oneof"`
}

type WendyComCommand_AppPushBegin struct {
	AppPushBegin *WendyComAppPushBeginParams `protobuf:"bytes,4,opt,name=app_push_begin,json=appPushBegin,proto3,oneof"`
}

type WendyComCommand_AppPushData struct {
	AppPushData *WendyComAppPushDataParams `protobuf:"bytes,5,opt,name=app_push_data,json=appPushData,proto3,oneof"`
}

type WendyComCommand_AppPushEnd struct {
	AppPushEnd *WendyComAppPushEndParams `protobuf:"bytes,6,opt,name=app_push_end,json=appPushEnd,proto3,oneof"`
}

type WendyComCommand_AppStart struct {
	AppStart *WendyComAppStartParams `protobuf:"bytes,7,opt,name=app_start,json=appStart,proto3,oneof"`
}

type WendyComCommand_AppStop struct {
	AppStop *WendyComAppStopParams `protobuf:"bytes,8,opt,name=app_stop,json=appStop,proto3,oneof"`
}

type WendyComCommand_GetDeviceIdentity struct {
	GetDeviceIdentity *WendyComGetDeviceIdentityParams `protobuf:"bytes,9,opt,name=get_device_identity,json=getDeviceIdentity,proto3,oneof"`
}

type WendyComCommand_GetDeviceInfo struct {
	GetDeviceInfo *WendyComGetDeviceInfoParams `protobuf:"bytes,10,opt,name=get_device_info,json=getDeviceInfo,proto3,oneof"`
}

type WendyComCommand_ConsoleAttach struct {
	ConsoleAttach *WendyComConsoleAttachParams `protobuf:"bytes,11,opt,name=console_attach,json=consoleAttach,proto3,oneof"`
}

type WendyComCommand_ConsoleDetach struct {
	ConsoleDetach *WendyComConsoleDetachParams `protobuf:"bytes,12,opt,name=console_detach,json=consoleDetach,proto3,oneof"`
}

type WendyComCommand_ConfPushBegin struct {
	ConfPushBegin *WendyComConfPushBeginParams `protobuf:"bytes,13,opt,name=conf_push_begin,json=confPushBegin,proto3,oneof"`
}

type WendyComCommand_ConfPushData struct {
	ConfPushData *WendyComConfPushDataParams `protobuf:"bytes,14,opt,name=conf_push_data,json=confPushData,proto3,oneof"`
}

type WendyComCommand_ConfPushEnd struct {
	ConfPushEnd *WendyComConfPushEndParams `protobuf:"bytes,15,opt,name=conf_push_end,json=confPushEnd,proto3,oneof"`
}

func (*WendyComCommand_Ping) isWendyComCommand_Params() {}

func (*WendyComCommand_Reboot) isWendyComCommand_Params() {}

func (*WendyComCommand_AppPushBegin) isWendyComCommand_Params() {}

func (*WendyComCommand_AppPushData) isWendyComCommand_Params() {}

func (*WendyComCommand_AppPushEnd) isWendyComCommand_Params() {}

func (*WendyComCommand_AppStart) isWendyComCommand_Params() {}

func (*WendyComCommand_AppStop) isWendyComCommand_Params() {}

func (*WendyComCommand_GetDeviceIdentity) isWendyComCommand_Params() {}

func (*WendyComCommand_GetDeviceInfo) isWendyComCommand_Params() {}

func (*WendyComCommand_ConsoleAttach) isWendyComCommand_Params() {}

func (*WendyComCommand_ConsoleDetach) isWendyComCommand_Params() {}

func (*WendyComCommand_ConfPushBegin) isWendyComCommand_Params() {}

func (*WendyComCommand_ConfPushData) isWendyComCommand_Params() {}

func (*WendyComCommand_ConfPushEnd) isWendyComCommand_Params() {}

// Response to a WendyComCommand — request_id matches the request.
type WendyComResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId uint32                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Result    WendyComResult         `protobuf:"varint,2,opt,name=result,proto3,enum=WendyComResult" json:"result,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*WendyComResponse_DeviceIdentity
	//	*WendyComResponse_DeviceInfo
	Data          isWendyComResponse_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComResponse) Reset() {
	*x = WendyComResponse{}
	mi := &file_wendy_com_msg_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComResponse) ProtoMessage() {}

func (x *WendyComResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_msg_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComResponse.ProtoReflect.Descriptor instead.
func (*WendyComResponse) Descriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{22}
}

func (x *WendyComResponse) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *WendyComResponse) GetResult() WendyComResult {
	if x != nil {
		return x.Result
	}
	return WendyComResult_WENDY_COM_RESULT_OK
}

func (x *WendyComResponse) GetData() isWendyComResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WendyComResponse) GetDeviceIdentity() *WendyComDeviceIdentity {
	if x != nil {
		if x, ok := x.Data.(*WendyComResponse_DeviceIdentity); ok {
			return x.DeviceIdentity
		}
	}
	return nil
}

func (x *WendyComResponse) GetDeviceInfo() *WendyComDeviceInfo {
	if x != nil {
		if x, ok := x.Data.(*WendyComResponse_DeviceInfo); ok {
			return x.DeviceInfo
		}
	}
	return nil
}

type isWendyComResponse_Data interface {
	isWendyComResponse_Data()
}

type WendyComResponse_DeviceIdentity struct {
	DeviceIdentity *WendyComDeviceIdentity `protobuf:"bytes,3,opt,name=device_identity,json=deviceIdentity,proto3,oneof"`
}

type WendyComResponse_DeviceInfo struct {
	DeviceInfo *WendyComDeviceInfo `protobuf:"bytes,4,opt,name=device_info,json=deviceInfo,proto3,oneof"`
}

func (*WendyComResponse_DeviceIdentity) isWendyComResponse_Data() {}

func (*WendyComResponse_DeviceInfo) isWendyComResponse_Data() {}

// Unsolicited device -> host or host -> device message.
type WendyComEvent struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	EventId uint32                 `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*WendyComEvent_ConsoleBegin
	//	*WendyComEvent_ConsoleData
	//	*WendyComEvent_ConsoleEnd
	Data          isWendyComEvent_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComEvent) Reset() {
	*x = WendyComEvent{}
	mi := &file_wendy_com_msg_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComEvent) ProtoMessage() {}

func (x *WendyComEvent) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_msg_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComEvent.ProtoReflect.Descriptor instead.
func (*WendyComEvent) Descriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{23}
}

func (x *WendyComEvent) GetEventId() uint32 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *WendyComEvent) GetData() isWendyComEvent_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WendyComEvent) GetConsoleBegin() *WendyComConsoleBegin {
	if x != nil {
		if x, ok := x.Data.(*WendyComEvent_ConsoleBegin); ok {
			return x.ConsoleBegin
		}
	}
	return nil
}

func (x *WendyComEvent) GetConsoleData() *WendyComConsoleData {
	if x != nil {
		if x, ok := x.Data.(*WendyComEvent_ConsoleData); ok {
			return x.ConsoleData
		}
	}
	return nil
}

func (x *WendyComEvent) GetConsoleEnd() *WendyComConsoleEnd {
	if x != nil {
		if x, ok := x.Data.(*WendyComEvent_ConsoleEnd); ok {
			return x.ConsoleEnd
		}
	}
	return nil
}

type isWendyComEvent_Data interface {
	isWendyComEvent_Data()
}

type WendyComEvent_ConsoleBegin struct {
	ConsoleBegin *WendyComConsoleBegin `protobuf:"bytes,2,opt,name=console_begin,json=consoleBegin,proto3,oneof"`
}

type WendyComEvent_ConsoleData struct {
	ConsoleData *WendyComConsoleData `protobuf:"bytes,3,opt,name=console_data,json=consoleData,proto3,oneof"`
}

type WendyComEvent_ConsoleEnd struct {
	ConsoleEnd *WendyComConsoleEnd `protobuf:"bytes,4,opt,name=console_end,json=consoleEnd,proto3,oneof"`
}

func (*WendyComEvent_ConsoleBegin) isWendyComEvent_Data() {}

func (*WendyComEvent_ConsoleData) isWendyComEvent_Data() {}

func (*WendyComEvent_ConsoleEnd) isWendyComEvent_Data() {}

// Channel management. The channel these messages operate on is the one
// carried by the channel byte of the frame header — OpenChannel arrives on
// the channel being opened, CloseChannel on the one being closed — so the
// bodies are empty presence markers. OpenChannel and CloseChannel are sent
// host -> device; ChannelState is sent device -> host. Devices that don't
// track channels may ignore these messages.
type WendyComOpenChannel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComOpenChannel) Reset() {
	*x = WendyComOpenChannel{}
	mi := &file_wendy_com_msg_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComOpenChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComOpenChannel) ProtoMessage() {}

func (x *WendyComOpenChannel) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_msg_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComOpenChannel.ProtoReflect.Descriptor instead.
func (*WendyComOpenChannel) Descriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{24}
}

type WendyComCloseChannel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComCloseChannel) Reset() {
	*x = WendyComCloseChannel{}
	mi := &file_wendy_com_msg_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComCloseChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComCloseChannel) ProtoMessage() {}

func (x *WendyComCloseChannel) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_msg_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComCloseChannel.ProtoReflect.Descriptor instead.
func (*WendyComCloseChannel) Descriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{25}
}

// Reports the state of the channel carried by the frame's channel byte,
// sent device -> host.
type WendyComChannelOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComChannelOpen) Reset() {
	*x = WendyComChannelOpen{}
	mi := &file_wendy_com_msg_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComChannelOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComChannelOpen) ProtoMessage() {}

func (x *WendyComChannelOpen) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_msg_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComChannelOpen.ProtoReflect.Descriptor instead.
func (*WendyComChannelOpen) Descriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{26}
}

type WendyComChannelClose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComChannelClose) Reset() {
	*x = WendyComChannelClose{}
	mi := &file_wendy_com_msg_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComChannelClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComChannelClose) ProtoMessage() {}

func (x *WendyComChannelClose) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_msg_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComChannelClose.ProtoReflect.Descriptor instead.
func (*WendyComChannelClose) Descriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{27}
}

type WendyComChannelError struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Reason        WendyComChannelErrorReason `protobuf:"varint,1,opt,name=reason,proto3,enum=WendyComChannelErrorReason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComChannelError) Reset() {
	*x = WendyComChannelError{}
	mi := &file_wendy_com_msg_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComChannelError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComChannelError) ProtoMessage() {}

func (x *WendyComChannelError) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_msg_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComChannelError.ProtoReflect.Descriptor instead.
func (*WendyComChannelError) Descriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{28}
}

func (x *WendyComChannelError) GetReason() WendyComChannelErrorReason {
	if x != nil {
		return x.Reason
	}
	return WendyComChannelErrorReason_WENDY_COM_CHANNEL_ERROR_REASON_NOT_OPEN
}

type WendyComChannelState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to State:
	//
	//	*WendyComChannelState_Open
	//	*WendyComChannelState_Close
	//	*WendyComChannelState_Error
	State         isWendyComChannelState_State `protobuf_oneof:"state"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComChannelState) Reset() {
	*x = WendyComChannelState{}
	mi := &file_wendy_com_msg_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComChannelState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComChannelState) ProtoMessage() {}

func (x *WendyComChannelState) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_msg_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComChannelState.ProtoReflect.Descriptor instead.
func (*WendyComChannelState) Descriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{29}
}

func (x *WendyComChannelState) GetState() isWendyComChannelState_State {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *WendyComChannelState) GetOpen() *WendyComChannelOpen {
	if x != nil {
		if x, ok := x.State.(*WendyComChannelState_Open); ok {
			return x.Open
		}
	}
	return nil
}

func (x *WendyComChannelState) GetClose() *WendyComChannelClose {
	if x != nil {
		if x, ok := x.State.(*WendyComChannelState_Close); ok {
			return x.Close
		}
	}
	return nil
}

func (x *WendyComChannelState) GetError() *WendyComChannelError {
	if x != nil {
		if x, ok := x.State.(*WendyComChannelState_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isWendyComChannelState_State interface {
	isWendyComChannelState_State()
}

type WendyComChannelState_Open struct {
	Open *WendyComChannelOpen `protobuf:"bytes,1,opt,name=open,proto3,oneof"`
}

type WendyComChannelState_Close struct {
	Close *WendyComChannelClose `protobuf:"bytes,2,opt,name=close,proto3,oneof"`
}

type WendyComChannelState_Error struct {
	Error *WendyComChannelError `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*WendyComChannelState_Open) isWendyComChannelState_State() {}

func (*WendyComChannelState_Close) isWendyComChannelState_State() {}

func (*WendyComChannelState_Error) isWendyComChannelState_State() {}

type WendyComService struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Cmd:
	//
	//	*WendyComService_OpenChannel
	//	*WendyComService_CloseChannel
	//	*WendyComService_ChannelState
	Cmd           isWendyComService_Cmd `protobuf_oneof:"cmd"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComService) Reset() {
	*x = WendyComService{}
	mi := &file_wendy_com_msg_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComService) ProtoMessage() {}

func (x *WendyComService) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_msg_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComService.ProtoReflect.Descriptor instead.
func (*WendyComService) Descriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{30}
}

func (x *WendyComService) GetCmd() isWendyComService_Cmd {
	if x != nil {
		return x.Cmd
	}
	return nil
}

func (x *WendyComService) GetOpenChannel() *WendyComOpenChannel {
	if x != nil {
		if x, ok := x.Cmd.(*WendyComService_OpenChannel); ok {
			return x.OpenChannel
		}
	}
	return nil
}

func (x *WendyComService) GetCloseChannel() *WendyComCloseChannel {
	if x != nil {
		if x, ok := x.Cmd.(*WendyComService_CloseChannel); ok {
			return x.CloseChannel
		}
	}
	return nil
}

func (x *WendyComService) GetChannelState() *WendyComChannelState {
	if x != nil {
		if x, ok := x.Cmd.(*WendyComService_ChannelState); ok {
			return x.ChannelState
		}
	}
	return nil
}

type isWendyComService_Cmd interface {
	isWendyComService_Cmd()
}

type WendyComService_OpenChannel struct {
	OpenChannel *WendyComOpenChannel `protobuf:"bytes,1,opt,name=open_channel,json=openChannel,proto3,oneof"`
}

type WendyComService_CloseChannel struct {
	CloseChannel *WendyComCloseChannel `protobuf:"bytes,2,opt,name=close_channel,json=closeChannel,proto3,oneof"`
}

type WendyComService_ChannelState struct {
	ChannelState *WendyComChannelState `protobuf:"bytes,3,opt,name=channel_state,json=channelState,proto3,oneof"`
}

func (*WendyComService_OpenChannel) isWendyComService_Cmd() {}

func (*WendyComService_CloseChannel) isWendyComService_Cmd() {}

func (*WendyComService_ChannelState) isWendyComService_Cmd() {}

// Base wrapper — every frame body, in either direction, is exactly one of
// these.
type WendyComMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*WendyComMessage_Handshake
	//	*WendyComMessage_Service
	//	*WendyComMessage_Command
	//	*WendyComMessage_Response
	//	*WendyComMessage_Event
	Msg           isWendyComMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComMessage) Reset() {
	*x = WendyComMessage{}
	mi := &file_wendy_com_msg_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComMessage) ProtoMessage() {}

func (x *WendyComMessage) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_msg_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComMessage.ProtoReflect.Descriptor instead.
func (*WendyComMessage) Descriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{31}
}

func (x *WendyComMessage) GetMsg() isWendyComMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *WendyComMessage) GetHandshake() *WendyComHandshake {
	if x != nil {
		if x, ok := x.Msg.(*WendyComMessage_Handshake); ok {
			return x.Handshake
		}
	}
	return nil
}

func (x *WendyComMessage) GetService() *WendyComService {
	if x != nil {
		if x, ok := x.Msg.(*WendyComMessage_Service); ok {
			return x.Service
		}
	}
	return nil
}

func (x *WendyComMessage) GetCommand() *WendyComCommand {
	if x != nil {
		if x, ok := x.Msg.(*WendyComMessage_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *WendyComMessage) GetResponse() *WendyComResponse {
	if x != nil {
		if x, ok := x.Msg.(*WendyComMessage_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *WendyComMessage) GetEvent() *WendyComEvent {
	if x != nil {
		if x, ok := x.Msg.(*WendyComMessage_Event); ok {
			return x.Event
		}
	}
	return nil
}

type isWendyComMessage_Msg interface {
	isWendyComMessage_Msg()
}

type WendyComMessage_Handshake struct {
	Handshake *WendyComHandshake `protobuf:"bytes,1,opt,name=handshake,proto3,oneof"`
}

type WendyComMessage_Service struct {
	Service *WendyComService `protobuf:"bytes,2,opt,name=service,proto3,oneof"`
}

type WendyComMessage_Command struct {
	Command *WendyComCommand `protobuf:"bytes,3,opt,name=command,proto3,oneof"`
}

type WendyComMessage_Response struct {
	Response *WendyComResponse `protobuf:"bytes,4,opt,name=response,proto3,oneof"`
}

type WendyComMessage_Event struct {
	Event *WendyComEvent `protobuf:"bytes,5,opt,name=event,proto3,oneof"`
}

func (*WendyComMessage_Handshake) isWendyComMessage_Msg() {}

func (*WendyComMessage_Service) isWendyComMessage_Msg() {}

func (*WendyComMessage_Command) isWendyComMessage_Msg() {}

func (*WendyComMessage_Response) isWendyComMessage_Msg() {}

func (*WendyComMessage_Event) isWendyComMessage_Msg() {}

var File_wendy_com_msg_proto protoreflect.FileDescriptor

const file_wendy_com_msg_proto_rawDesc = "" +
	"\n" +
	"\x13wendy_com_msg.proto\"E\n" +
	"\x17WendyComProtocolVersion\x12\x14\n" +
	"\x05major\x18\x01 \x01(\rR\x05major\x12\x14\n" +
	"\x05minor\x18\x02 \x01(\rR\x05minor\"j\n" +
	"\x11WendyComHandshake\x12!\n" +
	"\fhandshake_id\x18\x01 \x01(\rR\vhandshakeId\x122\n" +
	"\aversion\x18\x02 \x01(\v2\x18.WendyComProtocolVersionR\aversion\"\x14\n" +
	"\x12WendyComPingParams\"\x85\x01\n" +
	"\x14WendyComRebootParams\x12)\n" +
	"\x0eapp_auto_start\x18\x01 \x01(\bH\x00R\fappAutoStart\x88\x01\x01\x12/\n" +
	"\x14app_auto_start_delay\x18\x02 \x01(\rR\x11appAutoStartDelayB\x11\n" +
	"\x0f_app_auto_start\"]\n" +
	"\x1aWendyComAppPushBeginParams\x12\x12\n" +
	"\x04size\x18\x01 \x01(\rR\x04size\x12+\n" +
	"\bapp_type\x18\x02 \x01(\x0e2\x10.WendyComAppTypeR\aappType\"G\n" +
	"\x19WendyComAppPushDataParams\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\rR\x06offset\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\x1a\n" +
	"\x18WendyComAppPushEndParams\"\x18\n" +
	"\x16WendyComAppStartParams\"\x17\n" +
	"\x15WendyComAppStopParams\"\\\n" +
	"\x1bWendyComConfPushBeginParams\x12\x12\n" +
	"\x04size\x18\x01 \x01(\rR\x04size\x12)\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x15.WendyComConfPushModeR\x04mode\"H\n" +
	"\x1aWendyComConfPushDataParams\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\rR\x06offset\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\x1b\n" +
	"\x19WendyComConfPushEndParams\"!\n" +
	"\x1fWendyComGetDeviceIdentityParams\"_\n" +
	"\x16WendyComDeviceIdentity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\"\x1d\n" +
	"\x1bWendyComGetDeviceInfoParams\"p\n" +
	"\x1bWendyComConsoleAttachParams\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\rR\aeventId\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\rR\bduration\x12\x1a\n" +
	"\bblocking\x18\x03 \x01(\bR\bblocking\"8\n" +
	"\x1bWendyComConsoleDetachParams\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\rR\aeventId\"\x16\n" +
	"\x14WendyComConsoleBegin\"_\n" +
	"\x13WendyComConsoleData\x12\"\n" +
	"\x02io\x18\x01 \x01(\x0e2\x12.WendyComConsoleIoR\x02io\x12\x10\n" +
	"\x03gap\x18\x02 \x01(\bR\x03gap\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\x14\n" +
	"\x12WendyComConsoleEnd\"\xf4\x01\n" +
	"\x12WendyComDeviceInfo\x12\x0e\n" +
	"\x02os\x18\x01 \x01(\tR\x02os\x12\x1d\n" +
	"\n" +
	"os_version\x18\x02 \x01(\tR\tosVersion\x12)\n" +
	"\x10cpu_architecture\x18\x03 \x01(\tR\x0fcpuArchitecture\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\x12(\n" +
	"\x10wasm_app_support\x18\x05 \x01(\bR\x0ewasmAppSupport\x12,\n" +
	"\x12native_app_support\x18\x06 \x01(\bR\x10nativeAppSupport\x12\x14\n" +
	"\x05board\x18\a \x01(\tR\x05board\"\xc2\a\n" +
	"\x0fWendyComCommand\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\rR\trequestId\x12)\n" +
	"\x04ping\x18\x02 \x01(\v2\x13.WendyComPingParamsH\x00R\x04ping\x12/\n" +
	"\x06reboot\x18\x03 \x01(\v2\x15.WendyComRebootParamsH\x00R\x06reboot\x12C\n" +
	"\x0eapp_push_begin\x18\x04 \x01(\v2\x1b.WendyComAppPushBeginParamsH\x00R\fappPushBegin\x12@\n" +
	"\rapp_push_data\x18\x05 \x01(\v2\x1a.WendyComAppPushDataParamsH\x00R\vappPushData\x12=\n" +
	"\fapp_push_end\x18\x06 \x01(\v2\x19.WendyComAppPushEndParamsH\x00R\n" +
	"appPushEnd\x126\n" +
	"\tapp_start\x18\a \x01(\v2\x17.WendyComAppStartParamsH\x00R\bappStart\x123\n" +
	"\bapp_stop\x18\b \x01(\v2\x16.WendyComAppStopParamsH\x00R\aappStop\x12R\n" +
	"\x13get_device_identity\x18\t \x01(\v2 .WendyComGetDeviceIdentityParamsH\x00R\x11getDeviceIdentity\x12F\n" +
	"\x0fget_device_info\x18\n" +
	" \x01(\v2\x1c.WendyComGetDeviceInfoParamsH\x00R\rgetDeviceInfo\x12E\n" +
	"\x0econsole_attach\x18\v \x01(\v2\x1c.WendyComConsoleAttachParamsH\x00R\rconsoleAttach\x12E\n" +
	"\x0econsole_detach\x18\f \x01(\v2\x1c.WendyComConsoleDetachParamsH\x00R\rconsoleDetach\x12F\n" +
	"\x0fconf_push_begin\x18\r \x01(\v2\x1c.WendyComConfPushBeginParamsH\x00R\rconfPushBegin\x12C\n" +
	"\x0econf_push_data\x18\x0e \x01(\v2\x1b.WendyComConfPushDataParamsH\x00R\fconfPushData\x12@\n" +
	"\rconf_push_end\x18\x0f \x01(\v2\x1a.WendyComConfPushEndParamsH\x00R\vconfPushEndB\b\n" +
	"\x06params\"\xde\x01\n" +
	"\x10WendyComResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\rR\trequestId\x12'\n" +
	"\x06result\x18\x02 \x01(\x0e2\x0f.WendyComResultR\x06result\x12B\n" +
	"\x0fdevice_identity\x18\x03 \x01(\v2\x17.WendyComDeviceIdentityH\x00R\x0edeviceIdentity\x126\n" +
	"\vdevice_info\x18\x04 \x01(\v2\x13.WendyComDeviceInfoH\x00R\n" +
	"deviceInfoB\x06\n" +
	"\x04data\"\xe3\x01\n" +
	"\rWendyComEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\rR\aeventId\x12<\n" +
	"\rconsole_begin\x18\x02 \x01(\v2\x15.WendyComConsoleBeginH\x00R\fconsoleBegin\x129\n" +
	"\fconsole_data\x18\x03 \x01(\v2\x14.WendyComConsoleDataH\x00R\vconsoleData\x126\n" +
	"\vconsole_end\x18\x04 \x01(\v2\x13.WendyComConsoleEndH\x00R\n" +
	"consoleEndB\x06\n" +
	"\x04data\"\x15\n" +
	"\x13WendyComOpenChannel\"\x16\n" +
	"\x14WendyComCloseChannel\"\x15\n" +
	"\x13WendyComChannelOpen\"\x16\n" +
	"\x14WendyComChannelClose\"K\n" +
	"\x14WendyComChannelError\x123\n" +
	"\x06reason\x18\x01 \x01(\x0e2\x1b.WendyComChannelErrorReasonR\x06reason\"\xa9\x01\n" +
	"\x14WendyComChannelState\x12*\n" +
	"\x04open\x18\x01 \x01(\v2\x14.WendyComChannelOpenH\x00R\x04open\x12-\n" +
	"\x05close\x18\x02 \x01(\v2\x15.WendyComChannelCloseH\x00R\x05close\x12-\n" +
	"\x05error\x18\x03 \x01(\v2\x15.WendyComChannelErrorH\x00R\x05errorB\a\n" +
	"\x05state\"\xcf\x01\n" +
	"\x0fWendyComService\x129\n" +
	"\fopen_channel\x18\x01 \x01(\v2\x14.WendyComOpenChannelH\x00R\vopenChannel\x12<\n" +
	"\rclose_channel\x18\x02 \x01(\v2\x15.WendyComCloseChannelH\x00R\fcloseChannel\x12<\n" +
	"\rchannel_state\x18\x03 \x01(\v2\x15.WendyComChannelStateH\x00R\fchannelStateB\x05\n" +
	"\x03cmd\"\x81\x02\n" +
	"\x0fWendyComMessage\x122\n" +
	"\thandshake\x18\x01 \x01(\v2\x12.WendyComHandshakeH\x00R\thandshake\x12,\n" +
	"\aservice\x18\x02 \x01(\v2\x10.WendyComServiceH\x00R\aservice\x12,\n" +
	"\acommand\x18\x03 \x01(\v2\x10.WendyComCommandH\x00R\acommand\x12/\n" +
	"\bresponse\x18\x04 \x01(\v2\x11.WendyComResponseH\x00R\bresponse\x12&\n" +
	"\x05event\x18\x05 \x01(\v2\x0e.WendyComEventH\x00R\x05eventB\x05\n" +
	"\x03msg*M\n" +
	"\x0fWendyComAppType\x12\x1b\n" +
	"\x17WENDY_COM_APP_TYPE_WASM\x10\x00\x12\x1d\n" +
	"\x19WENDY_COM_APP_TYPE_NATIVE\x10\x01*a\n" +
	"\x14WendyComConfPushMode\x12$\n" +
	" WENDY_COM_CONF_PUSH_MODE_REPLACE\x10\x00\x12#\n" +
	"\x1fWENDY_COM_CONF_PUSH_MODE_UPDATE\x10\x01*\x8f\x01\n" +
	"\x11WendyComConsoleIo\x12'\n" +
	"#WENDY_COM_CONSOLE_IO_STANDARD_INPUT\x10\x00\x12(\n" +
	"$WENDY_COM_CONSOLE_IO_STANDARD_OUTPUT\x10\x01\x12'\n" +
	"#WENDY_COM_CONSOLE_IO_STANDARD_ERROR\x10\x02*\x9d\x02\n" +
	"\x0eWendyComResult\x12\x17\n" +
	"\x13WENDY_COM_RESULT_OK\x10\x00\x12\"\n" +
	"\x1eWENDY_COM_RESULT_UNKNOWN_ERROR\x10\x01\x12)\n" +
	"%WENDY_COM_RESULT_BAD_PROTOCOL_VERSION\x10\x02\x12\x1e\n" +
	"\x1aWENDY_COM_RESULT_BAD_STATE\x10\x03\x12\x19\n" +
	"\x15WENDY_COM_RESULT_BUSY\x10\x04\x12!\n" +
	"\x1dWENDY_COM_RESULT_BAD_APP_TYPE\x10\x05\x12!\n" +
	"\x1dWENDY_COM_RESULT_BAD_APP_SIZE\x10\x06\x12\"\n" +
	"\x1eWENDY_COM_RESULT_BAD_CONF_SIZE\x10\a*v\n" +
	"\x1aWendyComChannelErrorReason\x12+\n" +
	"'WENDY_COM_CHANNEL_ERROR_REASON_NOT_OPEN\x10\x00\x12+\n" +
	"'WENDY_COM_CHANNEL_ERROR_REASON_REJECTED\x10\x01b\x06proto3"

var (
	file_wendy_com_msg_proto_rawDescOnce sync.Once
	file_wendy_com_msg_proto_rawDescData []byte
)

func file_wendy_com_msg_proto_rawDescGZIP() []byte {
	file_wendy_com_msg_proto_rawDescOnce.Do(func() {
		file_wendy_com_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wendy_com_msg_proto_rawDesc), len(file_wendy_com_msg_proto_rawDesc)))
	})
	return file_wendy_com_msg_proto_rawDescData
}

var file_wendy_com_msg_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_wendy_com_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_wendy_com_msg_proto_goTypes = []any{
	(WendyComAppType)(0),                    // 0: WendyComAppType
	(WendyComConfPushMode)(0),               // 1: WendyComConfPushMode
	(WendyComConsoleIo)(0),                  // 2: WendyComConsoleIo
	(WendyComResult)(0),                     // 3: WendyComResult
	(WendyComChannelErrorReason)(0),         // 4: WendyComChannelErrorReason
	(*WendyComProtocolVersion)(nil),         // 5: WendyComProtocolVersion
	(*WendyComHandshake)(nil),               // 6: WendyComHandshake
	(*WendyComPingParams)(nil),              // 7: WendyComPingParams
	(*WendyComRebootParams)(nil),            // 8: WendyComRebootParams
	(*WendyComAppPushBeginParams)(nil),      // 9: WendyComAppPushBeginParams
	(*WendyComAppPushDataParams)(nil),       // 10: WendyComAppPushDataParams
	(*WendyComAppPushEndParams)(nil),        // 11: WendyComAppPushEndParams
	(*WendyComAppStartParams)(nil),          // 12: WendyComAppStartParams
	(*WendyComAppStopParams)(nil),           // 13: WendyComAppStopParams
	(*WendyComConfPushBeginParams)(nil),     // 14: WendyComConfPushBeginParams
	(*WendyComConfPushDataParams)(nil),      // 15: WendyComConfPushDataParams
	(*WendyComConfPushEndParams)(nil),       // 16: WendyComConfPushEndParams
	(*WendyComGetDeviceIdentityParams)(nil), // 17: WendyComGetDeviceIdentityParams
	(*WendyComDeviceIdentity)(nil),          // 18: WendyComDeviceIdentity
	(*WendyComGetDeviceInfoParams)(nil),     // 19: WendyComGetDeviceInfoParams
	(*WendyComConsoleAttachParams)(nil),     // 20: WendyComConsoleAttachParams
	(*WendyComConsoleDetachParams)(nil),     // 21: WendyComConsoleDetachParams
	(*WendyComConsoleBegin)(nil),            // 22: WendyComConsoleBegin
	(*WendyComConsoleData)(nil),             // 23: WendyComConsoleData
	(*WendyComConsoleEnd)(nil),              // 24: WendyComConsoleEnd
	(*WendyComDeviceInfo)(nil),              // 25: WendyComDeviceInfo
	(*WendyComCommand)(nil),                 // 26: WendyComCommand
	(*WendyComResponse)(nil),                // 27: WendyComResponse
	(*WendyComEvent)(nil),                   // 28: WendyComEvent
	(*WendyComOpenChannel)(nil),             // 29: WendyComOpenChannel
	(*WendyComCloseChannel)(nil),            // 30: WendyComCloseChannel
	(*WendyComChannelOpen)(nil),             // 31: WendyComChannelOpen
	(*WendyComChannelClose)(nil),            // 32: WendyComChannelClose
	(*WendyComChannelError)(nil),            // 33: WendyComChannelError
	(*WendyComChannelState)(nil),            // 34: WendyComChannelState
	(*WendyComService)(nil),                 // 35: WendyComService
	(*WendyComMessage)(nil),                 // 36: WendyComMessage
}
var file_wendy_com_msg_proto_depIdxs = []int32{
	5,  // 0: WendyComHandshake.version:type_name -> WendyComProtocolVersion
	0,  // 1: WendyComAppPushBeginParams.app_type:type_name -> WendyComAppType
	1,  // 2: WendyComConfPushBeginParams.mode:type_name -> WendyComConfPushMode
	2,  // 3: WendyComConsoleData.io:type_name -> WendyComConsoleIo
	7,  // 4: WendyComCommand.ping:type_name -> WendyComPingParams
	8,  // 5: WendyComCommand.reboot:type_name -> WendyComRebootParams
	9,  // 6: WendyComCommand.app_push_begin:type_name -> WendyComAppPushBeginParams
	10, // 7: WendyComCommand.app_push_data:type_name -> WendyComAppPushDataParams
	11, // 8: WendyComCommand.app_push_end:type_name -> WendyComAppPushEndParams
	12, // 9: WendyComCommand.app_start:type_name -> WendyComAppStartParams
	13, // 10: WendyComCommand.app_stop:type_name -> WendyComAppStopParams
	17, // 11: WendyComCommand.get_device_identity:type_name -> WendyComGetDeviceIdentityParams
	19, // 12: WendyComCommand.get_device_info:type_name -> WendyComGetDeviceInfoParams
	20, // 13: WendyComCommand.console_attach:type_name -> WendyComConsoleAttachParams
	21, // 14: WendyComCommand.console_detach:type_name -> WendyComConsoleDetachParams
	14, // 15: WendyComCommand.conf_push_begin:type_name -> WendyComConfPushBeginParams
	15, // 16: WendyComCommand.conf_push_data:type_name -> WendyComConfPushDataParams
	16, // 17: WendyComCommand.conf_push_end:type_name -> WendyComConfPushEndParams
	3,  // 18: WendyComResponse.result:type_name -> WendyComResult
	18, // 19: WendyComResponse.device_identity:type_name -> WendyComDeviceIdentity
	25, // 20: WendyComResponse.device_info:type_name -> WendyComDeviceInfo
	22, // 21: WendyComEvent.console_begin:type_name -> WendyComConsoleBegin
	23, // 22: WendyComEvent.console_data:type_name -> WendyComConsoleData
	24, // 23: WendyComEvent.console_end:type_name -> WendyComConsoleEnd
	4,  // 24: WendyComChannelError.reason:type_name -> WendyComChannelErrorReason
	31, // 25: WendyComChannelState.open:type_name -> WendyComChannelOpen
	32, // 26: WendyComChannelState.close:type_name -> WendyComChannelClose
	33, // 27: WendyComChannelState.error:type_name -> WendyComChannelError
	29, // 28: WendyComService.open_channel:type_name -> WendyComOpenChannel
	30, // 29: WendyComService.close_channel:type_name -> WendyComCloseChannel
	34, // 30: WendyComService.channel_state:type_name -> WendyComChannelState
	6,  // 31: WendyComMessage.handshake:type_name -> WendyComHandshake
	35, // 32: WendyComMessage.service:type_name -> WendyComService
	26, // 33: WendyComMessage.command:type_name -> WendyComCommand
	27, // 34: WendyComMessage.response:type_name -> WendyComResponse
	28, // 35: WendyComMessage.event:type_name -> WendyComEvent
	36, // [36:36] is the sub-list for method output_type
	36, // [36:36] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_wendy_com_msg_proto_init() }
func file_wendy_com_msg_proto_init() {
	if File_wendy_com_msg_proto != nil {
		return
	}
	file_wendy_com_msg_proto_msgTypes[3].OneofWrappers = []any{}
	file_wendy_com_msg_proto_msgTypes[21].OneofWrappers = []any{
		(*WendyComCommand_Ping)(nil),
		(*WendyComCommand_Reboot)(nil),
		(*WendyComCommand_AppPushBegin)(nil),
		(*WendyComCommand_AppPushData)(nil),
		(*WendyComCommand_AppPushEnd)(nil),
		(*WendyComCommand_AppStart)(nil),
		(*WendyComCommand_AppStop)(nil),
		(*WendyComCommand_GetDeviceIdentity)(nil),
		(*WendyComCommand_GetDeviceInfo)(nil),
		(*WendyComCommand_ConsoleAttach)(nil),
		(*WendyComCommand_ConsoleDetach)(nil),
		(*WendyComCommand_ConfPushBegin)(nil),
		(*WendyComCommand_ConfPushData)(nil),
		(*WendyComCommand_ConfPushEnd)(nil),
	}
	file_wendy_com_msg_proto_msgTypes[22].OneofWrappers = []any{
		(*WendyComResponse_DeviceIdentity)(nil),
		(*WendyComResponse_DeviceInfo)(nil),
	}
	file_wendy_com_msg_proto_msgTypes[23].OneofWrappers = []any{
		(*WendyComEvent_ConsoleBegin)(nil),
		(*WendyComEvent_ConsoleData)(nil),
		(*WendyComEvent_ConsoleEnd)(nil),
	}
	file_wendy_com_msg_proto_msgTypes[29].OneofWrappers = []any{
		(*WendyComChannelState_Open)(nil),
		(*WendyComChannelState_Close)(nil),
		(*WendyComChannelState_Error)(nil),
	}
	file_wendy_com_msg_proto_msgTypes[30].OneofWrappers = []any{
		(*WendyComService_OpenChannel)(nil),
		(*WendyComService_CloseChannel)(nil),
		(*WendyComService_ChannelState)(nil),
	}
	file_wendy_com_msg_proto_msgTypes[31].OneofWrappers = []any{
		(*WendyComMessage_Handshake)(nil),
		(*WendyComMessage_Service)(nil),
		(*WendyComMessage_Command)(nil),
		(*WendyComMessage_Response)(nil),
		(*WendyComMessage_Event)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wendy_com_msg_proto_rawDesc), len(file_wendy_com_msg_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wendy_com_msg_proto_goTypes,
		DependencyIndexes: file_wendy_com_msg_proto_depIdxs,
		EnumInfos:         file_wendy_com_msg_proto_enumTypes,
		MessageInfos:      file_wendy_com_msg_proto_msgTypes,
	}.Build()
	File_wendy_com_msg_proto = out.File
	file_wendy_com_msg_proto_goTypes = nil
	file_wendy_com_msg_proto_depIdxs = nil
}
