// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: wendy_com_msg.proto

package wendypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WendyComResult int32

const (
	WendyComResult_WENDY_COM_RESULT_OK            WendyComResult = 0
	WendyComResult_WENDY_COM_RESULT_UNKNOWN_ERROR WendyComResult = 1
	WendyComResult_WENDY_COM_RESULT_BAD_STATE     WendyComResult = 2
	WendyComResult_WENDY_COM_RESULT_BUSY          WendyComResult = 3
)

// Enum value maps for WendyComResult.
var (
	WendyComResult_name = map[int32]string{
		0: "WENDY_COM_RESULT_OK",
		1: "WENDY_COM_RESULT_UNKNOWN_ERROR",
		2: "WENDY_COM_RESULT_BAD_STATE",
		3: "WENDY_COM_RESULT_BUSY",
	}
	WendyComResult_value = map[string]int32{
		"WENDY_COM_RESULT_OK":            0,
		"WENDY_COM_RESULT_UNKNOWN_ERROR": 1,
		"WENDY_COM_RESULT_BAD_STATE":     2,
		"WENDY_COM_RESULT_BUSY":          3,
	}
)

func (x WendyComResult) Enum() *WendyComResult {
	p := new(WendyComResult)
	*p = x
	return p
}

func (x WendyComResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WendyComResult) Descriptor() protoreflect.EnumDescriptor {
	return file_wendy_com_msg_proto_enumTypes[0].Descriptor()
}

func (WendyComResult) Type() protoreflect.EnumType {
	return &file_wendy_com_msg_proto_enumTypes[0]
}

func (x WendyComResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WendyComResult.Descriptor instead.
func (WendyComResult) EnumDescriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{0}
}

// Response data for WENDY_COM_CMD_GET_PROTOCOL_VERSION
type WendyComProtocolVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Major         uint32                 `protobuf:"varint,1,opt,name=major,proto3" json:"major,omitempty"`
	Minor         uint32                 `protobuf:"varint,2,opt,name=minor,proto3" json:"minor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComProtocolVersion) Reset() {
	*x = WendyComProtocolVersion{}
	mi := &file_wendy_com_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComProtocolVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComProtocolVersion) ProtoMessage() {}

func (x *WendyComProtocolVersion) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComProtocolVersion.ProtoReflect.Descriptor instead.
func (*WendyComProtocolVersion) Descriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{0}
}

func (x *WendyComProtocolVersion) GetMajor() uint32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *WendyComProtocolVersion) GetMinor() uint32 {
	if x != nil {
		return x.Minor
	}
	return 0
}

// Command parameter messages — empty ones serve as presence markers.
type WendyComGetProtocolVersionParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComGetProtocolVersionParams) Reset() {
	*x = WendyComGetProtocolVersionParams{}
	mi := &file_wendy_com_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComGetProtocolVersionParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComGetProtocolVersionParams) ProtoMessage() {}

func (x *WendyComGetProtocolVersionParams) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComGetProtocolVersionParams.ProtoReflect.Descriptor instead.
func (*WendyComGetProtocolVersionParams) Descriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{1}
}

type WendyComPingParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComPingParams) Reset() {
	*x = WendyComPingParams{}
	mi := &file_wendy_com_msg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComPingParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComPingParams) ProtoMessage() {}

func (x *WendyComPingParams) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_msg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComPingParams.ProtoReflect.Descriptor instead.
func (*WendyComPingParams) Descriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{2}
}

type WendyComRebootParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComRebootParams) Reset() {
	*x = WendyComRebootParams{}
	mi := &file_wendy_com_msg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComRebootParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComRebootParams) ProtoMessage() {}

func (x *WendyComRebootParams) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_msg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComRebootParams.ProtoReflect.Descriptor instead.
func (*WendyComRebootParams) Descriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{3}
}

// Params for WENDY_COM_CMD_APP_PUSH_BEGIN
type WendyComAppPushBeginParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          uint32                 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComAppPushBeginParams) Reset() {
	*x = WendyComAppPushBeginParams{}
	mi := &file_wendy_com_msg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComAppPushBeginParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComAppPushBeginParams) ProtoMessage() {}

func (x *WendyComAppPushBeginParams) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_msg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComAppPushBeginParams.ProtoReflect.Descriptor instead.
func (*WendyComAppPushBeginParams) Descriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{4}
}

func (x *WendyComAppPushBeginParams) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

// Params for WENDY_COM_CMD_APP_PUSH_DATA
type WendyComAppPushDataParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint32                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComAppPushDataParams) Reset() {
	*x = WendyComAppPushDataParams{}
	mi := &file_wendy_com_msg_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComAppPushDataParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComAppPushDataParams) ProtoMessage() {}

func (x *WendyComAppPushDataParams) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_msg_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComAppPushDataParams.ProtoReflect.Descriptor instead.
func (*WendyComAppPushDataParams) Descriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{5}
}

func (x *WendyComAppPushDataParams) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *WendyComAppPushDataParams) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WendyComAppPushEndParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComAppPushEndParams) Reset() {
	*x = WendyComAppPushEndParams{}
	mi := &file_wendy_com_msg_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComAppPushEndParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComAppPushEndParams) ProtoMessage() {}

func (x *WendyComAppPushEndParams) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_msg_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComAppPushEndParams.ProtoReflect.Descriptor instead.
func (*WendyComAppPushEndParams) Descriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{6}
}

type WendyComAppStartParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComAppStartParams) Reset() {
	*x = WendyComAppStartParams{}
	mi := &file_wendy_com_msg_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComAppStartParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComAppStartParams) ProtoMessage() {}

func (x *WendyComAppStartParams) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_msg_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComAppStartParams.ProtoReflect.Descriptor instead.
func (*WendyComAppStartParams) Descriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{7}
}

type WendyComAppStopParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComAppStopParams) Reset() {
	*x = WendyComAppStopParams{}
	mi := &file_wendy_com_msg_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComAppStopParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComAppStopParams) ProtoMessage() {}

func (x *WendyComAppStopParams) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_msg_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComAppStopParams.ProtoReflect.Descriptor instead.
func (*WendyComAppStopParams) Descriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{8}
}

// Top-level command message — the oneof variant identifies the command.
type WendyComCommand struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId uint32                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Params:
	//
	//	*WendyComCommand_GetProtocolVersion
	//	*WendyComCommand_Ping
	//	*WendyComCommand_Reboot
	//	*WendyComCommand_AppPushBegin
	//	*WendyComCommand_AppPushData
	//	*WendyComCommand_AppPushEnd
	//	*WendyComCommand_AppStart
	//	*WendyComCommand_AppStop
	Params        isWendyComCommand_Params `protobuf_oneof:"params"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComCommand) Reset() {
	*x = WendyComCommand{}
	mi := &file_wendy_com_msg_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComCommand) ProtoMessage() {}

func (x *WendyComCommand) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_msg_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComCommand.ProtoReflect.Descriptor instead.
func (*WendyComCommand) Descriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{9}
}

func (x *WendyComCommand) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *WendyComCommand) GetParams() isWendyComCommand_Params {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *WendyComCommand) GetGetProtocolVersion() *WendyComGetProtocolVersionParams {
	if x != nil {
		if x, ok := x.Params.(*WendyComCommand_GetProtocolVersion); ok {
			return x.GetProtocolVersion
		}
	}
	return nil
}

func (x *WendyComCommand) GetPing() *WendyComPingParams {
	if x != nil {
		if x, ok := x.Params.(*WendyComCommand_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *WendyComCommand) GetReboot() *WendyComRebootParams {
	if x != nil {
		if x, ok := x.Params.(*WendyComCommand_Reboot); ok {
			return x.Reboot
		}
	}
	return nil
}

func (x *WendyComCommand) GetAppPushBegin() *WendyComAppPushBeginParams {
	if x != nil {
		if x, ok := x.Params.(*WendyComCommand_AppPushBegin); ok {
			return x.AppPushBegin
		}
	}
	return nil
}

func (x *WendyComCommand) GetAppPushData() *WendyComAppPushDataParams {
	if x != nil {
		if x, ok := x.Params.(*WendyComCommand_AppPushData); ok {
			return x.AppPushData
		}
	}
	return nil
}

func (x *WendyComCommand) GetAppPushEnd() *WendyComAppPushEndParams {
	if x != nil {
		if x, ok := x.Params.(*WendyComCommand_AppPushEnd); ok {
			return x.AppPushEnd
		}
	}
	return nil
}

func (x *WendyComCommand) GetAppStart() *WendyComAppStartParams {
	if x != nil {
		if x, ok := x.Params.(*WendyComCommand_AppStart); ok {
			return x.AppStart
		}
	}
	return nil
}

func (x *WendyComCommand) GetAppStop() *WendyComAppStopParams {
	if x != nil {
		if x, ok := x.Params.(*WendyComCommand_AppStop); ok {
			return x.AppStop
		}
	}
	return nil
}

type isWendyComCommand_Params interface {
	isWendyComCommand_Params()
}

type WendyComCommand_GetProtocolVersion struct {
	GetProtocolVersion *WendyComGetProtocolVersionParams `protobuf:"bytes,2,opt,name=get_protocol_version,json=getProtocolVersion,proto3,oneof"`
}

type WendyComCommand_Ping struct {
	Ping *WendyComPingParams `protobuf:"bytes,3,opt,name=ping,proto3,oneof"`
}

type WendyComCommand_Reboot struct {
	Reboot *WendyComRebootParams `protobuf:"bytes,4,opt,name=reboot,proto3,oneof"`
}

type WendyComCommand_AppPushBegin struct {
	AppPushBegin *WendyComAppPushBeginParams `protobuf:"bytes,5,opt,name=app_push_begin,json=appPushBegin,proto3,oneof"`
}

type WendyComCommand_AppPushData struct {
	AppPushData *WendyComAppPushDataParams `protobuf:"bytes,6,opt,name=app_push_data,json=appPushData,proto3,oneof"`
}

type WendyComCommand_AppPushEnd struct {
	AppPushEnd *WendyComAppPushEndParams `protobuf:"bytes,7,opt,name=app_push_end,json=appPushEnd,proto3,oneof"`
}

type WendyComCommand_AppStart struct {
	AppStart *WendyComAppStartParams `protobuf:"bytes,8,opt,name=app_start,json=appStart,proto3,oneof"`
}

type WendyComCommand_AppStop struct {
	AppStop *WendyComAppStopParams `protobuf:"bytes,9,opt,name=app_stop,json=appStop,proto3,oneof"`
}

func (*WendyComCommand_GetProtocolVersion) isWendyComCommand_Params() {}

func (*WendyComCommand_Ping) isWendyComCommand_Params() {}

func (*WendyComCommand_Reboot) isWendyComCommand_Params() {}

func (*WendyComCommand_AppPushBegin) isWendyComCommand_Params() {}

func (*WendyComCommand_AppPushData) isWendyComCommand_Params() {}

func (*WendyComCommand_AppPushEnd) isWendyComCommand_Params() {}

func (*WendyComCommand_AppStart) isWendyComCommand_Params() {}

func (*WendyComCommand_AppStop) isWendyComCommand_Params() {}

// Response to a WendyComCommand — request_id matches the request.
type WendyComResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId uint32                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Result    WendyComResult         `protobuf:"varint,2,opt,name=result,proto3,enum=WendyComResult" json:"result,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*WendyComResponse_ProtocolVersion
	Data          isWendyComResponse_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComResponse) Reset() {
	*x = WendyComResponse{}
	mi := &file_wendy_com_msg_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComResponse) ProtoMessage() {}

func (x *WendyComResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_msg_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComResponse.ProtoReflect.Descriptor instead.
func (*WendyComResponse) Descriptor() ([]byte, []int) {
	return file_wendy_com_msg_proto_rawDescGZIP(), []int{10}
}

func (x *WendyComResponse) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *WendyComResponse) GetResult() WendyComResult {
	if x != nil {
		return x.Result
	}
	return WendyComResult_WENDY_COM_RESULT_OK
}

func (x *WendyComResponse) GetData() isWendyComResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WendyComResponse) GetProtocolVersion() *WendyComProtocolVersion {
	if x != nil {
		if x, ok := x.Data.(*WendyComResponse_ProtocolVersion); ok {
			return x.ProtocolVersion
		}
	}
	return nil
}

type isWendyComResponse_Data interface {
	isWendyComResponse_Data()
}

type WendyComResponse_ProtocolVersion struct {
	ProtocolVersion *WendyComProtocolVersion `protobuf:"bytes,3,opt,name=protocol_version,json=protocolVersion,proto3,oneof"`
}

func (*WendyComResponse_ProtocolVersion) isWendyComResponse_Data() {}

var File_wendy_com_msg_proto protoreflect.FileDescriptor

const file_wendy_com_msg_proto_rawDesc = "" +
	"\n" +
	"\x13wendy_com_msg.proto\"E\n" +
	"\x17WendyComProtocolVersion\x12\x14\n" +
	"\x05major\x18\x01 \x01(\rR\x05major\x12\x14\n" +
	"\x05minor\x18\x02 \x01(\rR\x05minor\"\"\n" +
	" WendyComGetProtocolVersionParams\"\x14\n" +
	"\x12WendyComPingParams\"\x16\n" +
	"\x14WendyComRebootParams\"0\n" +
	"\x1aWendyComAppPushBeginParams\x12\x12\n" +
	"\x04size\x18\x01 \x01(\rR\x04size\"G\n" +
	"\x19WendyComAppPushDataParams\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\rR\x06offset\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\x1a\n" +
	"\x18WendyComAppPushEndParams\"\x18\n" +
	"\x16WendyComAppStartParams\"\x17\n" +
	"\x15WendyComAppStopParams\"\xa0\x04\n" +
	"\x0fWendyComCommand\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\rR\trequestId\x12U\n" +
	"\x14get_protocol_version\x18\x02 \x01(\v2!.WendyComGetProtocolVersionParamsH\x00R\x12getProtocolVersion\x12)\n" +
	"\x04ping\x18\x03 \x01(\v2\x13.WendyComPingParamsH\x00R\x04ping\x12/\n" +
	"\x06reboot\x18\x04 \x01(\v2\x15.WendyComRebootParamsH\x00R\x06reboot\x12C\n" +
	"\x0eapp_push_begin\x18\x05 \x01(\v2\x1b.WendyComAppPushBeginParamsH\x00R\fappPushBegin\x12@\n" +
	"\rapp_push_data\x18\x06 \x01(\v2\x1a.WendyComAppPushDataParamsH\x00R\vappPushData\x12=\n" +
	"\fapp_push_end\x18\a \x01(\v2\x19.WendyComAppPushEndParamsH\x00R\n" +
	"appPushEnd\x126\n" +
	"\tapp_start\x18\b \x01(\v2\x17.WendyComAppStartParamsH\x00R\bappStart\x123\n" +
	"\bapp_stop\x18\t \x01(\v2\x16.WendyComAppStopParamsH\x00R\aappStopB\b\n" +
	"\x06params\"\xa9\x01\n" +
	"\x10WendyComResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\rR\trequestId\x12'\n" +
	"\x06result\x18\x02 \x01(\x0e2\x0f.WendyComResultR\x06result\x12E\n" +
	"\x10protocol_version\x18\x03 \x01(\v2\x18.WendyComProtocolVersionH\x00R\x0fprotocolVersionB\x06\n" +
	"\x04data*\x88\x01\n" +
	"\x0eWendyComResult\x12\x17\n" +
	"\x13WENDY_COM_RESULT_OK\x10\x00\x12\"\n" +
	"\x1eWENDY_COM_RESULT_UNKNOWN_ERROR\x10\x01\x12\x1e\n" +
	"\x1aWENDY_COM_RESULT_BAD_STATE\x10\x02\x12\x19\n" +
	"\x15WENDY_COM_RESULT_BUSY\x10\x03b\x06proto3"

var (
	file_wendy_com_msg_proto_rawDescOnce sync.Once
	file_wendy_com_msg_proto_rawDescData []byte
)

func file_wendy_com_msg_proto_rawDescGZIP() []byte {
	file_wendy_com_msg_proto_rawDescOnce.Do(func() {
		file_wendy_com_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wendy_com_msg_proto_rawDesc), len(file_wendy_com_msg_proto_rawDesc)))
	})
	return file_wendy_com_msg_proto_rawDescData
}

var file_wendy_com_msg_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wendy_com_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_wendy_com_msg_proto_goTypes = []any{
	(WendyComResult)(0),                      // 0: WendyComResult
	(*WendyComProtocolVersion)(nil),          // 1: WendyComProtocolVersion
	(*WendyComGetProtocolVersionParams)(nil), // 2: WendyComGetProtocolVersionParams
	(*WendyComPingParams)(nil),               // 3: WendyComPingParams
	(*WendyComRebootParams)(nil),             // 4: WendyComRebootParams
	(*WendyComAppPushBeginParams)(nil),       // 5: WendyComAppPushBeginParams
	(*WendyComAppPushDataParams)(nil),        // 6: WendyComAppPushDataParams
	(*WendyComAppPushEndParams)(nil),         // 7: WendyComAppPushEndParams
	(*WendyComAppStartParams)(nil),           // 8: WendyComAppStartParams
	(*WendyComAppStopParams)(nil),            // 9: WendyComAppStopParams
	(*WendyComCommand)(nil),                  // 10: WendyComCommand
	(*WendyComResponse)(nil),                 // 11: WendyComResponse
}
var file_wendy_com_msg_proto_depIdxs = []int32{
	2,  // 0: WendyComCommand.get_protocol_version:type_name -> WendyComGetProtocolVersionParams
	3,  // 1: WendyComCommand.ping:type_name -> WendyComPingParams
	4,  // 2: WendyComCommand.reboot:type_name -> WendyComRebootParams
	5,  // 3: WendyComCommand.app_push_begin:type_name -> WendyComAppPushBeginParams
	6,  // 4: WendyComCommand.app_push_data:type_name -> WendyComAppPushDataParams
	7,  // 5: WendyComCommand.app_push_end:type_name -> WendyComAppPushEndParams
	8,  // 6: WendyComCommand.app_start:type_name -> WendyComAppStartParams
	9,  // 7: WendyComCommand.app_stop:type_name -> WendyComAppStopParams
	0,  // 8: WendyComResponse.result:type_name -> WendyComResult
	1,  // 9: WendyComResponse.protocol_version:type_name -> WendyComProtocolVersion
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_wendy_com_msg_proto_init() }
func file_wendy_com_msg_proto_init() {
	if File_wendy_com_msg_proto != nil {
		return
	}
	file_wendy_com_msg_proto_msgTypes[9].OneofWrappers = []any{
		(*WendyComCommand_GetProtocolVersion)(nil),
		(*WendyComCommand_Ping)(nil),
		(*WendyComCommand_Reboot)(nil),
		(*WendyComCommand_AppPushBegin)(nil),
		(*WendyComCommand_AppPushData)(nil),
		(*WendyComCommand_AppPushEnd)(nil),
		(*WendyComCommand_AppStart)(nil),
		(*WendyComCommand_AppStop)(nil),
	}
	file_wendy_com_msg_proto_msgTypes[10].OneofWrappers = []any{
		(*WendyComResponse_ProtocolVersion)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wendy_com_msg_proto_rawDesc), len(file_wendy_com_msg_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wendy_com_msg_proto_goTypes,
		DependencyIndexes: file_wendy_com_msg_proto_depIdxs,
		EnumInfos:         file_wendy_com_msg_proto_enumTypes,
		MessageInfos:      file_wendy_com_msg_proto_msgTypes,
	}.Build()
	File_wendy_com_msg_proto = out.File
	file_wendy_com_msg_proto_goTypes = nil
	file_wendy_com_msg_proto_depIdxs = nil
}
