// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.0
// source: sensorlink.proto

package sensorlinkpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VideoFormat_Codec int32

const (
	VideoFormat_CODEC_UNSPECIFIED VideoFormat_Codec = 0
	VideoFormat_MJPEG             VideoFormat_Codec = 1
	VideoFormat_H264              VideoFormat_Codec = 2
)

// Enum value maps for VideoFormat_Codec.
var (
	VideoFormat_Codec_name = map[int32]string{
		0: "CODEC_UNSPECIFIED",
		1: "MJPEG",
		2: "H264",
	}
	VideoFormat_Codec_value = map[string]int32{
		"CODEC_UNSPECIFIED": 0,
		"MJPEG":             1,
		"H264":              2,
	}
)

func (x VideoFormat_Codec) Enum() *VideoFormat_Codec {
	p := new(VideoFormat_Codec)
	*p = x
	return p
}

func (x VideoFormat_Codec) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VideoFormat_Codec) Descriptor() protoreflect.EnumDescriptor {
	return file_sensorlink_proto_enumTypes[0].Descriptor()
}

func (VideoFormat_Codec) Type() protoreflect.EnumType {
	return &file_sensorlink_proto_enumTypes[0]
}

func (x VideoFormat_Codec) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VideoFormat_Codec.Descriptor instead.
func (VideoFormat_Codec) EnumDescriptor() ([]byte, []int) {
	return file_sensorlink_proto_rawDescGZIP(), []int{0, 0}
}

type AudioFormat_Codec int32

const (
	AudioFormat_CODEC_UNSPECIFIED AudioFormat_Codec = 0
	AudioFormat_PCM_S16LE         AudioFormat_Codec = 1
	AudioFormat_OPUS              AudioFormat_Codec = 2
)

// Enum value maps for AudioFormat_Codec.
var (
	AudioFormat_Codec_name = map[int32]string{
		0: "CODEC_UNSPECIFIED",
		1: "PCM_S16LE",
		2: "OPUS",
	}
	AudioFormat_Codec_value = map[string]int32{
		"CODEC_UNSPECIFIED": 0,
		"PCM_S16LE":         1,
		"OPUS":              2,
	}
)

func (x AudioFormat_Codec) Enum() *AudioFormat_Codec {
	p := new(AudioFormat_Codec)
	*p = x
	return p
}

func (x AudioFormat_Codec) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AudioFormat_Codec) Descriptor() protoreflect.EnumDescriptor {
	return file_sensorlink_proto_enumTypes[1].Descriptor()
}

func (AudioFormat_Codec) Type() protoreflect.EnumType {
	return &file_sensorlink_proto_enumTypes[1]
}

func (x AudioFormat_Codec) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AudioFormat_Codec.Descriptor instead.
func (AudioFormat_Codec) EnumDescriptor() ([]byte, []int) {
	return file_sensorlink_proto_rawDescGZIP(), []int{1, 0}
}

type SensorDescriptor_Kind int32

const (
	SensorDescriptor_KIND_UNSPECIFIED SensorDescriptor_Kind = 0
	SensorDescriptor_CAMERA           SensorDescriptor_Kind = 1
	SensorDescriptor_MICROPHONE       SensorDescriptor_Kind = 2
	SensorDescriptor_SENSOR           SensorDescriptor_Kind = 3
)

// Enum value maps for SensorDescriptor_Kind.
var (
	SensorDescriptor_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "CAMERA",
		2: "MICROPHONE",
		3: "SENSOR",
	}
	SensorDescriptor_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"CAMERA":           1,
		"MICROPHONE":       2,
		"SENSOR":           3,
	}
)

func (x SensorDescriptor_Kind) Enum() *SensorDescriptor_Kind {
	p := new(SensorDescriptor_Kind)
	*p = x
	return p
}

func (x SensorDescriptor_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SensorDescriptor_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_sensorlink_proto_enumTypes[2].Descriptor()
}

func (SensorDescriptor_Kind) Type() protoreflect.EnumType {
	return &file_sensorlink_proto_enumTypes[2]
}

func (x SensorDescriptor_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SensorDescriptor_Kind.Descriptor instead.
func (SensorDescriptor_Kind) EnumDescriptor() ([]byte, []int) {
	return file_sensorlink_proto_rawDescGZIP(), []int{3, 0}
}

type VideoFormat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Codec         VideoFormat_Codec      `protobuf:"varint,1,opt,name=codec,proto3,enum=wendy.lite.sensorlink.VideoFormat_Codec" json:"codec,omitempty"`
	Width         uint32                 `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Fps           uint32                 `protobuf:"varint,4,opt,name=fps,proto3" json:"fps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoFormat) Reset() {
	*x = VideoFormat{}
	mi := &file_sensorlink_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoFormat) ProtoMessage() {}

func (x *VideoFormat) ProtoReflect() protoreflect.Message {
	mi := &file_sensorlink_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoFormat.ProtoReflect.Descriptor instead.
func (*VideoFormat) Descriptor() ([]byte, []int) {
	return file_sensorlink_proto_rawDescGZIP(), []int{0}
}

func (x *VideoFormat) GetCodec() VideoFormat_Codec {
	if x != nil {
		return x.Codec
	}
	return VideoFormat_CODEC_UNSPECIFIED
}

func (x *VideoFormat) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *VideoFormat) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *VideoFormat) GetFps() uint32 {
	if x != nil {
		return x.Fps
	}
	return 0
}

type AudioFormat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Codec         AudioFormat_Codec      `protobuf:"varint,1,opt,name=codec,proto3,enum=wendy.lite.sensorlink.AudioFormat_Codec" json:"codec,omitempty"`
	SampleRate    uint32                 `protobuf:"varint,2,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	Channels      uint32                 `protobuf:"varint,3,opt,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioFormat) Reset() {
	*x = AudioFormat{}
	mi := &file_sensorlink_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioFormat) ProtoMessage() {}

func (x *AudioFormat) ProtoReflect() protoreflect.Message {
	mi := &file_sensorlink_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioFormat.ProtoReflect.Descriptor instead.
func (*AudioFormat) Descriptor() ([]byte, []int) {
	return file_sensorlink_proto_rawDescGZIP(), []int{1}
}

func (x *AudioFormat) GetCodec() AudioFormat_Codec {
	if x != nil {
		return x.Codec
	}
	return AudioFormat_CODEC_UNSPECIFIED
}

func (x *AudioFormat) GetSampleRate() uint32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *AudioFormat) GetChannels() uint32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

type SensorFormat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        string                 `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"` // type id, e.g. "wendy.imu.v1"
	RateHz        uint32                 `protobuf:"varint,2,opt,name=rate_hz,json=rateHz,proto3" json:"rate_hz,omitempty"`
	SampleBytes   uint32                 `protobuf:"varint,3,opt,name=sample_bytes,json=sampleBytes,proto3" json:"sample_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorFormat) Reset() {
	*x = SensorFormat{}
	mi := &file_sensorlink_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorFormat) ProtoMessage() {}

func (x *SensorFormat) ProtoReflect() protoreflect.Message {
	mi := &file_sensorlink_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorFormat.ProtoReflect.Descriptor instead.
func (*SensorFormat) Descriptor() ([]byte, []int) {
	return file_sensorlink_proto_rawDescGZIP(), []int{2}
}

func (x *SensorFormat) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *SensorFormat) GetRateHz() uint32 {
	if x != nil {
		return x.RateHz
	}
	return 0
}

func (x *SensorFormat) GetSampleBytes() uint32 {
	if x != nil {
		return x.SampleBytes
	}
	return 0
}

type SensorDescriptor struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ChannelId uint32                 `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Kind      SensorDescriptor_Kind  `protobuf:"varint,2,opt,name=kind,proto3,enum=wendy.lite.sensorlink.SensorDescriptor_Kind" json:"kind,omitempty"`
	Name      string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Format:
	//
	//	*SensorDescriptor_Video
	//	*SensorDescriptor_Audio
	//	*SensorDescriptor_Sensor
	Format        isSensorDescriptor_Format `protobuf_oneof:"format"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorDescriptor) Reset() {
	*x = SensorDescriptor{}
	mi := &file_sensorlink_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorDescriptor) ProtoMessage() {}

func (x *SensorDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_sensorlink_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorDescriptor.ProtoReflect.Descriptor instead.
func (*SensorDescriptor) Descriptor() ([]byte, []int) {
	return file_sensorlink_proto_rawDescGZIP(), []int{3}
}

func (x *SensorDescriptor) GetChannelId() uint32 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *SensorDescriptor) GetKind() SensorDescriptor_Kind {
	if x != nil {
		return x.Kind
	}
	return SensorDescriptor_KIND_UNSPECIFIED
}

func (x *SensorDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SensorDescriptor) GetFormat() isSensorDescriptor_Format {
	if x != nil {
		return x.Format
	}
	return nil
}

func (x *SensorDescriptor) GetVideo() *VideoFormat {
	if x != nil {
		if x, ok := x.Format.(*SensorDescriptor_Video); ok {
			return x.Video
		}
	}
	return nil
}

func (x *SensorDescriptor) GetAudio() *AudioFormat {
	if x != nil {
		if x, ok := x.Format.(*SensorDescriptor_Audio); ok {
			return x.Audio
		}
	}
	return nil
}

func (x *SensorDescriptor) GetSensor() *SensorFormat {
	if x != nil {
		if x, ok := x.Format.(*SensorDescriptor_Sensor); ok {
			return x.Sensor
		}
	}
	return nil
}

type isSensorDescriptor_Format interface {
	isSensorDescriptor_Format()
}

type SensorDescriptor_Video struct {
	Video *VideoFormat `protobuf:"bytes,4,opt,name=video,proto3,oneof"`
}

type SensorDescriptor_Audio struct {
	Audio *AudioFormat `protobuf:"bytes,5,opt,name=audio,proto3,oneof"`
}

type SensorDescriptor_Sensor struct {
	Sensor *SensorFormat `protobuf:"bytes,6,opt,name=sensor,proto3,oneof"`
}

func (*SensorDescriptor_Video) isSensorDescriptor_Format() {}

func (*SensorDescriptor_Audio) isSensorDescriptor_Format() {}

func (*SensorDescriptor_Sensor) isSensorDescriptor_Format() {}

type SensorManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceAssetId int32                  `protobuf:"varint,1,opt,name=device_asset_id,json=deviceAssetId,proto3" json:"device_asset_id,omitempty"`
	Sensors       []*SensorDescriptor    `protobuf:"bytes,2,rep,name=sensors,proto3" json:"sensors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorManifest) Reset() {
	*x = SensorManifest{}
	mi := &file_sensorlink_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorManifest) ProtoMessage() {}

func (x *SensorManifest) ProtoReflect() protoreflect.Message {
	mi := &file_sensorlink_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorManifest.ProtoReflect.Descriptor instead.
func (*SensorManifest) Descriptor() ([]byte, []int) {
	return file_sensorlink_proto_rawDescGZIP(), []int{4}
}

func (x *SensorManifest) GetDeviceAssetId() int32 {
	if x != nil {
		return x.DeviceAssetId
	}
	return 0
}

func (x *SensorManifest) GetSensors() []*SensorDescriptor {
	if x != nil {
		return x.Sensors
	}
	return nil
}

type GetSensorManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSensorManifest) Reset() {
	*x = GetSensorManifest{}
	mi := &file_sensorlink_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSensorManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSensorManifest) ProtoMessage() {}

func (x *GetSensorManifest) ProtoReflect() protoreflect.Message {
	mi := &file_sensorlink_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSensorManifest.ProtoReflect.Descriptor instead.
func (*GetSensorManifest) Descriptor() ([]byte, []int) {
	return file_sensorlink_proto_rawDescGZIP(), []int{5}
}

type Subscribe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     []uint32               `protobuf:"varint,1,rep,packed,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscribe) Reset() {
	*x = Subscribe{}
	mi := &file_sensorlink_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscribe) ProtoMessage() {}

func (x *Subscribe) ProtoReflect() protoreflect.Message {
	mi := &file_sensorlink_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscribe.ProtoReflect.Descriptor instead.
func (*Subscribe) Descriptor() ([]byte, []int) {
	return file_sensorlink_proto_rawDescGZIP(), []int{6}
}

func (x *Subscribe) GetChannelId() []uint32 {
	if x != nil {
		return x.ChannelId
	}
	return nil
}

type Unsubscribe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     []uint32               `protobuf:"varint,1,rep,packed,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Unsubscribe) Reset() {
	*x = Unsubscribe{}
	mi := &file_sensorlink_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unsubscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unsubscribe) ProtoMessage() {}

func (x *Unsubscribe) ProtoReflect() protoreflect.Message {
	mi := &file_sensorlink_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unsubscribe.ProtoReflect.Descriptor instead.
func (*Unsubscribe) Descriptor() ([]byte, []int) {
	return file_sensorlink_proto_rawDescGZIP(), []int{7}
}

func (x *Unsubscribe) GetChannelId() []uint32 {
	if x != nil {
		return x.ChannelId
	}
	return nil
}

type SensorFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     uint32                 `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Seq           uint32                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	TsUs          uint64                 `protobuf:"varint,3,opt,name=ts_us,json=tsUs,proto3" json:"ts_us,omitempty"`
	Flags         uint32                 `protobuf:"varint,4,opt,name=flags,proto3" json:"flags,omitempty"` // bit0 = keyframe
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorFrame) Reset() {
	*x = SensorFrame{}
	mi := &file_sensorlink_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorFrame) ProtoMessage() {}

func (x *SensorFrame) ProtoReflect() protoreflect.Message {
	mi := &file_sensorlink_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorFrame.ProtoReflect.Descriptor instead.
func (*SensorFrame) Descriptor() ([]byte, []int) {
	return file_sensorlink_proto_rawDescGZIP(), []int{8}
}

func (x *SensorFrame) GetChannelId() uint32 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *SensorFrame) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *SensorFrame) GetTsUs() uint64 {
	if x != nil {
		return x.TsUs
	}
	return 0
}

func (x *SensorFrame) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *SensorFrame) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TsUs          uint64                 `protobuf:"varint,1,opt,name=ts_us,json=tsUs,proto3" json:"ts_us,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_sensorlink_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_sensorlink_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_sensorlink_proto_rawDescGZIP(), []int{9}
}

func (x *Ping) GetTsUs() uint64 {
	if x != nil {
		return x.TsUs
	}
	return 0
}

// Every message on the wire is an Envelope, so framing needs only one type.
type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*Envelope_Manifest
	//	*Envelope_Subscribe
	//	*Envelope_Frame
	//	*Envelope_Ping
	Msg           isEnvelope_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_sensorlink_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_sensorlink_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_sensorlink_proto_rawDescGZIP(), []int{10}
}

func (x *Envelope) GetMsg() isEnvelope_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *Envelope) GetManifest() *SensorManifest {
	if x != nil {
		if x, ok := x.Msg.(*Envelope_Manifest); ok {
			return x.Manifest
		}
	}
	return nil
}

func (x *Envelope) GetSubscribe() *Subscribe {
	if x != nil {
		if x, ok := x.Msg.(*Envelope_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

func (x *Envelope) GetFrame() *SensorFrame {
	if x != nil {
		if x, ok := x.Msg.(*Envelope_Frame); ok {
			return x.Frame
		}
	}
	return nil
}

func (x *Envelope) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Msg.(*Envelope_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isEnvelope_Msg interface {
	isEnvelope_Msg()
}

type Envelope_Manifest struct {
	Manifest *SensorManifest `protobuf:"bytes,1,opt,name=manifest,proto3,oneof"`
}

type Envelope_Subscribe struct {
	Subscribe *Subscribe `protobuf:"bytes,2,opt,name=subscribe,proto3,oneof"`
}

type Envelope_Frame struct {
	Frame *SensorFrame `protobuf:"bytes,3,opt,name=frame,proto3,oneof"`
}

type Envelope_Ping struct {
	Ping *Ping `protobuf:"bytes,4,opt,name=ping,proto3,oneof"`
}

func (*Envelope_Manifest) isEnvelope_Msg() {}

func (*Envelope_Subscribe) isEnvelope_Msg() {}

func (*Envelope_Frame) isEnvelope_Msg() {}

func (*Envelope_Ping) isEnvelope_Msg() {}

var File_sensorlink_proto protoreflect.FileDescriptor

const file_sensorlink_proto_rawDesc = "" +
	"\n" +
	"\x10sensorlink.proto\x12\x15wendy.lite.sensorlink\"\xc2\x01\n" +
	"\vVideoFormat\x12>\n" +
	"\x05codec\x18\x01 \x01(\x0e2(.wendy.lite.sensorlink.VideoFormat.CodecR\x05codec\x12\x14\n" +
	"\x05width\x18\x02 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\rR\x06height\x12\x10\n" +
	"\x03fps\x18\x04 \x01(\rR\x03fps\"3\n" +
	"\x05Codec\x12\x15\n" +
	"\x11CODEC_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05MJPEG\x10\x01\x12\b\n" +
	"\x04H264\x10\x02\"\xc3\x01\n" +
	"\vAudioFormat\x12>\n" +
	"\x05codec\x18\x01 \x01(\x0e2(.wendy.lite.sensorlink.AudioFormat.CodecR\x05codec\x12\x1f\n" +
	"\vsample_rate\x18\x02 \x01(\rR\n" +
	"sampleRate\x12\x1a\n" +
	"\bchannels\x18\x03 \x01(\rR\bchannels\"7\n" +
	"\x05Codec\x12\x15\n" +
	"\x11CODEC_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tPCM_S16LE\x10\x01\x12\b\n" +
	"\x04OPUS\x10\x02\"b\n" +
	"\fSensorFormat\x12\x16\n" +
	"\x06schema\x18\x01 \x01(\tR\x06schema\x12\x17\n" +
	"\arate_hz\x18\x02 \x01(\rR\x06rateHz\x12!\n" +
	"\fsample_bytes\x18\x03 \x01(\rR\vsampleBytes\"\x8e\x03\n" +
	"\x10SensorDescriptor\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\rR\tchannelId\x12@\n" +
	"\x04kind\x18\x02 \x01(\x0e2,.wendy.lite.sensorlink.SensorDescriptor.KindR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12:\n" +
	"\x05video\x18\x04 \x01(\v2\".wendy.lite.sensorlink.VideoFormatH\x00R\x05video\x12:\n" +
	"\x05audio\x18\x05 \x01(\v2\".wendy.lite.sensorlink.AudioFormatH\x00R\x05audio\x12=\n" +
	"\x06sensor\x18\x06 \x01(\v2#.wendy.lite.sensorlink.SensorFormatH\x00R\x06sensor\"D\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06CAMERA\x10\x01\x12\x0e\n" +
	"\n" +
	"MICROPHONE\x10\x02\x12\n" +
	"\n" +
	"\x06SENSOR\x10\x03B\b\n" +
	"\x06format\"{\n" +
	"\x0eSensorManifest\x12&\n" +
	"\x0fdevice_asset_id\x18\x01 \x01(\x05R\rdeviceAssetId\x12A\n" +
	"\asensors\x18\x02 \x03(\v2'.wendy.lite.sensorlink.SensorDescriptorR\asensors\"\x13\n" +
	"\x11GetSensorManifest\"*\n" +
	"\tSubscribe\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x03(\rR\tchannelId\",\n" +
	"\vUnsubscribe\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x03(\rR\tchannelId\"\x83\x01\n" +
	"\vSensorFrame\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\rR\tchannelId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\rR\x03seq\x12\x13\n" +
	"\x05ts_us\x18\x03 \x01(\x04R\x04tsUs\x12\x14\n" +
	"\x05flags\x18\x04 \x01(\rR\x05flags\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\"\x1b\n" +
	"\x04Ping\x12\x13\n" +
	"\x05ts_us\x18\x01 \x01(\x04R\x04tsUs\"\x87\x02\n" +
	"\bEnvelope\x12C\n" +
	"\bmanifest\x18\x01 \x01(\v2%.wendy.lite.sensorlink.SensorManifestH\x00R\bmanifest\x12@\n" +
	"\tsubscribe\x18\x02 \x01(\v2 .wendy.lite.sensorlink.SubscribeH\x00R\tsubscribe\x12:\n" +
	"\x05frame\x18\x03 \x01(\v2\".wendy.lite.sensorlink.SensorFrameH\x00R\x05frame\x121\n" +
	"\x04ping\x18\x04 \x01(\v2\x1b.wendy.lite.sensorlink.PingH\x00R\x04pingB\x05\n" +
	"\x03msgb\x06proto3"

var (
	file_sensorlink_proto_rawDescOnce sync.Once
	file_sensorlink_proto_rawDescData []byte
)

func file_sensorlink_proto_rawDescGZIP() []byte {
	file_sensorlink_proto_rawDescOnce.Do(func() {
		file_sensorlink_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sensorlink_proto_rawDesc), len(file_sensorlink_proto_rawDesc)))
	})
	return file_sensorlink_proto_rawDescData
}

var file_sensorlink_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_sensorlink_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_sensorlink_proto_goTypes = []any{
	(VideoFormat_Codec)(0),     // 0: wendy.lite.sensorlink.VideoFormat.Codec
	(AudioFormat_Codec)(0),     // 1: wendy.lite.sensorlink.AudioFormat.Codec
	(SensorDescriptor_Kind)(0), // 2: wendy.lite.sensorlink.SensorDescriptor.Kind
	(*VideoFormat)(nil),        // 3: wendy.lite.sensorlink.VideoFormat
	(*AudioFormat)(nil),        // 4: wendy.lite.sensorlink.AudioFormat
	(*SensorFormat)(nil),       // 5: wendy.lite.sensorlink.SensorFormat
	(*SensorDescriptor)(nil),   // 6: wendy.lite.sensorlink.SensorDescriptor
	(*SensorManifest)(nil),     // 7: wendy.lite.sensorlink.SensorManifest
	(*GetSensorManifest)(nil),  // 8: wendy.lite.sensorlink.GetSensorManifest
	(*Subscribe)(nil),          // 9: wendy.lite.sensorlink.Subscribe
	(*Unsubscribe)(nil),        // 10: wendy.lite.sensorlink.Unsubscribe
	(*SensorFrame)(nil),        // 11: wendy.lite.sensorlink.SensorFrame
	(*Ping)(nil),               // 12: wendy.lite.sensorlink.Ping
	(*Envelope)(nil),           // 13: wendy.lite.sensorlink.Envelope
}
var file_sensorlink_proto_depIdxs = []int32{
	0,  // 0: wendy.lite.sensorlink.VideoFormat.codec:type_name -> wendy.lite.sensorlink.VideoFormat.Codec
	1,  // 1: wendy.lite.sensorlink.AudioFormat.codec:type_name -> wendy.lite.sensorlink.AudioFormat.Codec
	2,  // 2: wendy.lite.sensorlink.SensorDescriptor.kind:type_name -> wendy.lite.sensorlink.SensorDescriptor.Kind
	3,  // 3: wendy.lite.sensorlink.SensorDescriptor.video:type_name -> wendy.lite.sensorlink.VideoFormat
	4,  // 4: wendy.lite.sensorlink.SensorDescriptor.audio:type_name -> wendy.lite.sensorlink.AudioFormat
	5,  // 5: wendy.lite.sensorlink.SensorDescriptor.sensor:type_name -> wendy.lite.sensorlink.SensorFormat
	6,  // 6: wendy.lite.sensorlink.SensorManifest.sensors:type_name -> wendy.lite.sensorlink.SensorDescriptor
	7,  // 7: wendy.lite.sensorlink.Envelope.manifest:type_name -> wendy.lite.sensorlink.SensorManifest
	9,  // 8: wendy.lite.sensorlink.Envelope.subscribe:type_name -> wendy.lite.sensorlink.Subscribe
	11, // 9: wendy.lite.sensorlink.Envelope.frame:type_name -> wendy.lite.sensorlink.SensorFrame
	12, // 10: wendy.lite.sensorlink.Envelope.ping:type_name -> wendy.lite.sensorlink.Ping
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_sensorlink_proto_init() }
func file_sensorlink_proto_init() {
	if File_sensorlink_proto != nil {
		return
	}
	file_sensorlink_proto_msgTypes[3].OneofWrappers = []any{
		(*SensorDescriptor_Video)(nil),
		(*SensorDescriptor_Audio)(nil),
		(*SensorDescriptor_Sensor)(nil),
	}
	file_sensorlink_proto_msgTypes[10].OneofWrappers = []any{
		(*Envelope_Manifest)(nil),
		(*Envelope_Subscribe)(nil),
		(*Envelope_Frame)(nil),
		(*Envelope_Ping)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sensorlink_proto_rawDesc), len(file_sensorlink_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sensorlink_proto_goTypes,
		DependencyIndexes: file_sensorlink_proto_depIdxs,
		EnumInfos:         file_sensorlink_proto_enumTypes,
		MessageInfos:      file_sensorlink_proto_msgTypes,
	}.Build()
	File_sensorlink_proto = out.File
	file_sensorlink_proto_goTypes = nil
	file_sensorlink_proto_depIdxs = nil
}
