// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: wendy_com_tunnel_service.proto

package tunnelpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_wendy_com_tunnel_service_proto protoreflect.FileDescriptor

const file_wendy_com_tunnel_service_proto_rawDesc = "" +
	"\n" +
	"\x1ewendy_com_tunnel_service.proto\x1a\x1awendy_com_tunnel_msg.proto2c\n" +
	"\x1bWendyComTunnelBrokerService\x12D\n" +
	"\x0eWendyComTunnel\x12\x16.WendyComTunnelMessage\x1a\x16.WendyComTunnelMessage(\x010\x01b\x06proto3"

var file_wendy_com_tunnel_service_proto_goTypes = []any{
	(*WendyComTunnelMessage)(nil), // 0: WendyComTunnelMessage
}
var file_wendy_com_tunnel_service_proto_depIdxs = []int32{
	0, // 0: WendyComTunnelBrokerService.WendyComTunnel:input_type -> WendyComTunnelMessage
	0, // 1: WendyComTunnelBrokerService.WendyComTunnel:output_type -> WendyComTunnelMessage
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wendy_com_tunnel_service_proto_init() }
func file_wendy_com_tunnel_service_proto_init() {
	if File_wendy_com_tunnel_service_proto != nil {
		return
	}
	file_wendy_com_tunnel_msg_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wendy_com_tunnel_service_proto_rawDesc), len(file_wendy_com_tunnel_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wendy_com_tunnel_service_proto_goTypes,
		DependencyIndexes: file_wendy_com_tunnel_service_proto_depIdxs,
	}.Build()
	File_wendy_com_tunnel_service_proto = out.File
	file_wendy_com_tunnel_service_proto_goTypes = nil
	file_wendy_com_tunnel_service_proto_depIdxs = nil
}
