// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.0
// source: wendy_com_tunnel_service.proto

package tunnelpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WendyComTunnelBrokerService_WendyComTunnel_FullMethodName = "/WendyComTunnelBrokerService/WendyComTunnel"
)

// WendyComTunnelBrokerServiceClient is the client API for WendyComTunnelBrokerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WendyComTunnelBrokerServiceClient interface {
	// The client's first message must be open; everything after, in both
	// directions, is payload. Stream lifetime == channel lifetime.
	WendyComTunnel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WendyComTunnelMessage, WendyComTunnelMessage], error)
}

type wendyComTunnelBrokerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWendyComTunnelBrokerServiceClient(cc grpc.ClientConnInterface) WendyComTunnelBrokerServiceClient {
	return &wendyComTunnelBrokerServiceClient{cc}
}

func (c *wendyComTunnelBrokerServiceClient) WendyComTunnel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WendyComTunnelMessage, WendyComTunnelMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WendyComTunnelBrokerService_ServiceDesc.Streams[0], WendyComTunnelBrokerService_WendyComTunnel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WendyComTunnelMessage, WendyComTunnelMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WendyComTunnelBrokerService_WendyComTunnelClient = grpc.BidiStreamingClient[WendyComTunnelMessage, WendyComTunnelMessage]

// WendyComTunnelBrokerServiceServer is the server API for WendyComTunnelBrokerService service.
// All implementations must embed UnimplementedWendyComTunnelBrokerServiceServer
// for forward compatibility.
type WendyComTunnelBrokerServiceServer interface {
	// The client's first message must be open; everything after, in both
	// directions, is payload. Stream lifetime == channel lifetime.
	WendyComTunnel(grpc.BidiStreamingServer[WendyComTunnelMessage, WendyComTunnelMessage]) error
	mustEmbedUnimplementedWendyComTunnelBrokerServiceServer()
}

// UnimplementedWendyComTunnelBrokerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWendyComTunnelBrokerServiceServer struct{}

func (UnimplementedWendyComTunnelBrokerServiceServer) WendyComTunnel(grpc.BidiStreamingServer[WendyComTunnelMessage, WendyComTunnelMessage]) error {
	return status.Error(codes.Unimplemented, "method WendyComTunnel not implemented")
}
func (UnimplementedWendyComTunnelBrokerServiceServer) mustEmbedUnimplementedWendyComTunnelBrokerServiceServer() {
}
func (UnimplementedWendyComTunnelBrokerServiceServer) testEmbeddedByValue() {}

// UnsafeWendyComTunnelBrokerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WendyComTunnelBrokerServiceServer will
// result in compilation errors.
type UnsafeWendyComTunnelBrokerServiceServer interface {
	mustEmbedUnimplementedWendyComTunnelBrokerServiceServer()
}

func RegisterWendyComTunnelBrokerServiceServer(s grpc.ServiceRegistrar, srv WendyComTunnelBrokerServiceServer) {
	// If the following call panics, it indicates UnimplementedWendyComTunnelBrokerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WendyComTunnelBrokerService_ServiceDesc, srv)
}

func _WendyComTunnelBrokerService_WendyComTunnel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WendyComTunnelBrokerServiceServer).WendyComTunnel(&grpc.GenericServerStream[WendyComTunnelMessage, WendyComTunnelMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WendyComTunnelBrokerService_WendyComTunnelServer = grpc.BidiStreamingServer[WendyComTunnelMessage, WendyComTunnelMessage]

// WendyComTunnelBrokerService_ServiceDesc is the grpc.ServiceDesc for WendyComTunnelBrokerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WendyComTunnelBrokerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "WendyComTunnelBrokerService",
	HandlerType: (*WendyComTunnelBrokerServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WendyComTunnel",
			Handler:       _WendyComTunnelBrokerService_WendyComTunnel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "wendy_com_tunnel_service.proto",
}
