// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: wendy_com_tunnel_msg.proto

package tunnelpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// First and only non-payload client message on a tunnel stream. Identifies
// the target device. For now the broker trusts this value; later it is
// cross-checked against enrollment data.
type WendyComTunnelOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       uint32                 `protobuf:"varint,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComTunnelOpen) Reset() {
	*x = WendyComTunnelOpen{}
	mi := &file_wendy_com_tunnel_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComTunnelOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComTunnelOpen) ProtoMessage() {}

func (x *WendyComTunnelOpen) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_tunnel_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComTunnelOpen.ProtoReflect.Descriptor instead.
func (*WendyComTunnelOpen) Descriptor() ([]byte, []int) {
	return file_wendy_com_tunnel_msg_proto_rawDescGZIP(), []int{0}
}

func (x *WendyComTunnelOpen) GetAssetId() uint32 {
	if x != nil {
		return x.AssetId
	}
	return 0
}

// One bare protobuf-encoded WendyComMessage body — no 8-byte link header.
// The broker adds/strips the header and owns the channel byte.
type WendyComTunnelPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bytes         []byte                 `protobuf:"bytes,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComTunnelPayload) Reset() {
	*x = WendyComTunnelPayload{}
	mi := &file_wendy_com_tunnel_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComTunnelPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComTunnelPayload) ProtoMessage() {}

func (x *WendyComTunnelPayload) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_tunnel_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComTunnelPayload.ProtoReflect.Descriptor instead.
func (*WendyComTunnelPayload) Descriptor() ([]byte, []int) {
	return file_wendy_com_tunnel_msg_proto_rawDescGZIP(), []int{1}
}

func (x *WendyComTunnelPayload) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

type WendyComTunnelMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*WendyComTunnelMessage_Open
	//	*WendyComTunnelMessage_Payload
	Msg           isWendyComTunnelMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WendyComTunnelMessage) Reset() {
	*x = WendyComTunnelMessage{}
	mi := &file_wendy_com_tunnel_msg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WendyComTunnelMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WendyComTunnelMessage) ProtoMessage() {}

func (x *WendyComTunnelMessage) ProtoReflect() protoreflect.Message {
	mi := &file_wendy_com_tunnel_msg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WendyComTunnelMessage.ProtoReflect.Descriptor instead.
func (*WendyComTunnelMessage) Descriptor() ([]byte, []int) {
	return file_wendy_com_tunnel_msg_proto_rawDescGZIP(), []int{2}
}

func (x *WendyComTunnelMessage) GetMsg() isWendyComTunnelMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *WendyComTunnelMessage) GetOpen() *WendyComTunnelOpen {
	if x != nil {
		if x, ok := x.Msg.(*WendyComTunnelMessage_Open); ok {
			return x.Open
		}
	}
	return nil
}

func (x *WendyComTunnelMessage) GetPayload() *WendyComTunnelPayload {
	if x != nil {
		if x, ok := x.Msg.(*WendyComTunnelMessage_Payload); ok {
			return x.Payload
		}
	}
	return nil
}

type isWendyComTunnelMessage_Msg interface {
	isWendyComTunnelMessage_Msg()
}

type WendyComTunnelMessage_Open struct {
	Open *WendyComTunnelOpen `protobuf:"bytes,1,opt,name=open,proto3,oneof"`
}

type WendyComTunnelMessage_Payload struct {
	Payload *WendyComTunnelPayload `protobuf:"bytes,2,opt,name=payload,proto3,oneof"`
}

func (*WendyComTunnelMessage_Open) isWendyComTunnelMessage_Msg() {}

func (*WendyComTunnelMessage_Payload) isWendyComTunnelMessage_Msg() {}

var File_wendy_com_tunnel_msg_proto protoreflect.FileDescriptor

const file_wendy_com_tunnel_msg_proto_rawDesc = "" +
	"\n" +
	"\x1awendy_com_tunnel_msg.proto\"/\n" +
	"\x12WendyComTunnelOpen\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\rR\aassetId\"-\n" +
	"\x15WendyComTunnelPayload\x12\x14\n" +
	"\x05bytes\x18\x01 \x01(\fR\x05bytes\"}\n" +
	"\x15WendyComTunnelMessage\x12)\n" +
	"\x04open\x18\x01 \x01(\v2\x13.WendyComTunnelOpenH\x00R\x04open\x122\n" +
	"\apayload\x18\x02 \x01(\v2\x16.WendyComTunnelPayloadH\x00R\apayloadB\x05\n" +
	"\x03msgb\x06proto3"

var (
	file_wendy_com_tunnel_msg_proto_rawDescOnce sync.Once
	file_wendy_com_tunnel_msg_proto_rawDescData []byte
)

func file_wendy_com_tunnel_msg_proto_rawDescGZIP() []byte {
	file_wendy_com_tunnel_msg_proto_rawDescOnce.Do(func() {
		file_wendy_com_tunnel_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wendy_com_tunnel_msg_proto_rawDesc), len(file_wendy_com_tunnel_msg_proto_rawDesc)))
	})
	return file_wendy_com_tunnel_msg_proto_rawDescData
}

var file_wendy_com_tunnel_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_wendy_com_tunnel_msg_proto_goTypes = []any{
	(*WendyComTunnelOpen)(nil),    // 0: WendyComTunnelOpen
	(*WendyComTunnelPayload)(nil), // 1: WendyComTunnelPayload
	(*WendyComTunnelMessage)(nil), // 2: WendyComTunnelMessage
}
var file_wendy_com_tunnel_msg_proto_depIdxs = []int32{
	0, // 0: WendyComTunnelMessage.open:type_name -> WendyComTunnelOpen
	1, // 1: WendyComTunnelMessage.payload:type_name -> WendyComTunnelPayload
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_wendy_com_tunnel_msg_proto_init() }
func file_wendy_com_tunnel_msg_proto_init() {
	if File_wendy_com_tunnel_msg_proto != nil {
		return
	}
	file_wendy_com_tunnel_msg_proto_msgTypes[2].OneofWrappers = []any{
		(*WendyComTunnelMessage_Open)(nil),
		(*WendyComTunnelMessage_Payload)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wendy_com_tunnel_msg_proto_rawDesc), len(file_wendy_com_tunnel_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wendy_com_tunnel_msg_proto_goTypes,
		DependencyIndexes: file_wendy_com_tunnel_msg_proto_depIdxs,
		MessageInfos:      file_wendy_com_tunnel_msg_proto_msgTypes,
	}.Build()
	File_wendy_com_tunnel_msg_proto = out.File
	file_wendy_com_tunnel_msg_proto_goTypes = nil
	file_wendy_com_tunnel_msg_proto_depIdxs = nil
}
